/* Solar System Explorer — per-planet detail content (bilingual).
   Hotspot lat/lon are in degrees on the equirectangular texture
   (lon -180 = left edge). Moons: tex = real map (see textures/), style = procedural fallback. */
var PLANET_CONTENT = {

  sun: {
    subtitle: { en: 'Our Star', zh: '我們的恆星' },
    camDist: 12,
    selfLit: true,
    hotspots: [
      { lat: -15, lon: -30, color: '#ffb347', icon: '🕶️',
        en: { kicker: 'Sunspots', title: 'The Dark Spots', question: 'What are the dark spots?',
          text: "Sunspots are places where the Sun's magnetic field is so strong that it blocks heat from rising up. They are cooler than the rest of the surface, about 3,500 degrees instead of 5,500, so they look dark. But each one is still hotter than any fire on Earth, and many are bigger than our whole planet!" },
        zh: { kicker: '太陽黑子', title: '黑黑的斑點', question: '那些黑黑的點是什麼？',
          text: '太陽黑子是太陽磁場特別強的地方，強到把往上冒的熱氣擋住了。它們比周圍的表面涼一點，大約 3500 度而不是 5500 度，所以看起來比較暗。但每一個黑子都比地球上任何火焰還燙，而且很多黑子比整個地球還大！' } },
      { lat: 10, lon: 90, offset: 1.22, color: '#fff1a8', icon: '💥',
        en: { kicker: 'Solar Flare', title: 'A Giant Explosion', question: 'What is a solar flare?',
          text: 'A solar flare is a huge explosion on the Sun. Twisted magnetic fields snap like a stretched rubber band and release as much energy as billions of bombs in just a few minutes! The light reaches Earth eight minutes later, and can make radios crackle and give us extra-bright northern lights.' },
        zh: { kicker: '太陽閃焰', title: '巨大的爆炸', question: '什麼是太陽閃焰？',
          text: '太陽閃焰是太陽上的超級大爆炸。扭在一起的磁場像被拉緊的橡皮筋一樣「啪」地彈開，在短短幾分鐘裡放出相當於幾十億顆炸彈的能量！閃焰的光八分鐘後就會到達地球，可能讓無線電變得沙沙響，還會讓極光變得特別亮。' } },
      { lat: -40, lon: 160, offset: 1.18, color: '#ff8c42', icon: '🌉',
        en: { kicker: 'Prominence', title: 'Loops of Fire', question: 'What are those arches of fire?',
          text: 'Prominences are enormous arches of glowing gas held up by magnetic fields. One loop can stretch farther than thirty Earths lined up in a row! They can hang above the Sun for weeks before falling back down or bursting out into space.' },
        zh: { kicker: '日珥', title: '火焰拱橋', question: '那些火焰拱橋是什麼？',
          text: '日珥是被磁場撐起來的巨大發光氣體拱橋。一道日珥可以比三十顆地球排成一排還長！它們可以在太陽上方掛好幾個星期，然後掉回去，或是「砰」地噴向太空。' } },
      { lat: 30, lon: -110, color: '#ffd166', icon: '🍿',
        en: { kicker: 'Surface', title: 'A Boiling Sea of Gas', question: 'Why does the surface look bumpy?',
          text: 'The Sun has no solid ground at all. Its surface is a boiling sea of gas made of cells called granules, each about the size of a small country. Hot gas bubbles up in the middle of each cell, cools, and sinks down at the edges, just like soup bubbling in a pot.' },
        zh: { kicker: '表面', title: '滾燙的氣體海洋', question: '為什麼表面看起來一顆一顆的？',
          text: '太陽完全沒有堅硬的地面。它的表面是一片滾燙的氣體海洋，分成一格一格叫「米粒組織」的小格子，每一格大約有一個小國家那麼大。熱氣從每一格的中間冒上來，變涼之後再從邊邊沉下去，就像鍋子裡咕嚕咕嚕滾的湯。' } },
      { lat: 60, lon: 30, offset: 1.3, color: '#ffffff', icon: '👑',
        en: { kicker: 'Corona', title: 'The Sun\'s Crown', question: 'What is the glow around the Sun?',
          text: "The corona is the Sun's outer atmosphere, and it is one of the Sun's biggest mysteries: it is hundreds of times hotter than the surface, over a million degrees! We can only see it with our own eyes during a total solar eclipse, when the Moon covers the bright disc." },
        zh: { kicker: '日冕', title: '太陽的皇冠', question: '太陽周圍的光暈是什麼？',
          text: '日冕是太陽最外層的大氣，也是太陽最大的謎團之一：它比太陽表面熱好幾百倍，超過一百萬度！我們只有在日全食的時候，月亮把亮亮的太陽盤面遮住時，才能用眼睛看到它。' } },
      { lat: -5, lon: 40, color: '#ff5a3c', icon: '⚛️',
        en: { kicker: 'Core', title: 'Where Light Is Made', question: 'How does the Sun make light?',
          text: 'Deep in the core it is fifteen million degrees, and hydrogen atoms get squeezed together so hard that they turn into helium. This is called fusion. Every second it changes four million tonnes of matter into pure light and heat. The sunlight you see today was made in the core thousands of years ago!' },
        zh: { kicker: '核心', title: '製造光的地方', question: '太陽是怎麼發光的？',
          text: '在太陽的核心深處有一千五百萬度，氫原子被擠壓得非常用力，變成了氦。這叫做「核融合」。每一秒鐘，它把四百萬公噸的物質變成純粹的光和熱。你今天看到的陽光，是幾千年前在核心裡製造出來的！' } }
    ],
    moons: [],
    facts: [
      { icon: '⭐', en: { title: 'A star, not a planet', text: 'The Sun is a star, just like the ones you see at night, only much closer. It looks the same size as the Moon in our sky because it is 400 times bigger, but also 400 times farther away.' }, zh: { title: '它是恆星，不是行星', text: '太陽是一顆恆星，和晚上看到的星星一樣，只是離我們近很多。它在天空中看起來和月亮一樣大，是因為它比月亮大 400 倍，但也遠了 400 倍。' } },
      { icon: '🌍', en: { title: '1.3 million Earths', text: 'About 1.3 million Earths could fit inside the Sun. It holds 99.8 percent of all the stuff in the whole solar system!' }, zh: { title: '130 萬顆地球', text: '太陽可以裝下大約 130 萬顆地球。整個太陽系 99.8% 的物質都在太陽裡！' } },
      { icon: '⏳', en: { title: 'Eight-minute-old light', text: 'Sunlight takes 8 minutes and 20 seconds to reach Earth. If the Sun switched off, we would not notice for 8 whole minutes!' }, zh: { title: '八分鐘前的光', text: '陽光要飛 8 分 20 秒才到達地球。如果太陽突然關掉，我們要整整 8 分鐘後才會發現！' } },
      { icon: '🔄', en: { title: 'It spins, but not all at once', text: 'Because the Sun is made of gas, its middle spins faster than its poles: once every 25 days at the equator, but 35 days near the poles.' }, zh: { title: '會轉，但轉得不一樣快', text: '因為太陽是氣體做的，它的中間轉得比兩極快：赤道 25 天轉一圈，兩極附近要 35 天。' } },
      { icon: '📅', en: { title: 'An eleven-year mood cycle', text: 'Every 11 years the Sun gets busy, with lots of sunspots and flares, then calms down again. Scientists watch this cycle to protect satellites and astronauts.' }, zh: { title: '11 年的心情週期', text: '每 11 年太陽會變得很活躍，出現很多黑子和閃焰，然後又安靜下來。科學家觀察這個週期，來保護衛星和太空人。' } },
      { icon: '🌬️', en: { title: 'The solar wind', text: 'The Sun constantly blows a wind of tiny particles into space at over 400 kilometers per second. It is what pushes comet tails so they always point away from the Sun.' }, zh: { title: '太陽風', text: '太陽不停地把微小粒子吹向太空，速度超過每秒 400 公里。彗星的尾巴之所以永遠背對太陽，就是被太陽風吹的。' } },
      { icon: '🚀', en: { title: 'A spacecraft touched it', text: "In 2021 NASA's Parker Solar Probe flew right through the corona. It is the fastest thing humans have ever built, zooming at 690,000 kilometers per hour!" }, zh: { title: '有太空船碰過它', text: '2021 年 NASA 的帕克太陽探測器直接穿過了日冕。它是人類做過最快的東西，速度高達每小時 69 萬公里！' } },
      { icon: '🔥', en: { title: 'Halfway through its life', text: 'The Sun is about 4.6 billion years old and will shine for about 5 billion more. Then it will swell into a red giant, so big it may swallow Mercury and Venus.' }, zh: { title: '一生過了一半', text: '太陽大約 46 億歲了，還可以再發光大約 50 億年。之後它會膨脹成一顆紅巨星，大到可能把水星和金星都吞掉。' } },
      { icon: '🕶️', en: { title: 'Never look straight at it', text: 'The Sun is so bright it can hurt your eyes in seconds. Never look at it directly, and only use special eclipse glasses to watch an eclipse.' }, zh: { title: '千萬不要直接看它', text: '太陽亮到幾秒鐘就可能傷害眼睛。絕對不要直接盯著太陽看，看日食一定要用專門的日食眼鏡。' } }
    ]
  },

  mercury: {
    subtitle: { en: 'The Speedy Little Planet', zh: '跑得最快的小行星' },
    camDist: 11,
    hotspots: [
      { lat: 30, lon: -160, color: '#ffd28a', icon: '🎯',
        en: { kicker: 'Caloris Basin', title: 'The Giant Dent', question: 'What is that huge round mark?',
          text: "That's the Caloris Basin, a crater about 1,500 kilometers wide! A giant space rock smashed into Mercury almost four billion years ago. The crash was so strong that it even wrinkled the ground on the opposite side of the planet." },
        zh: { kicker: '卡洛里盆地', title: '超級大凹洞', question: '那個巨大的圓形痕跡是什麼？',
          text: '那是卡洛里盆地，一個寬約 1500 公里的隕石坑！大約四十億年前，一顆巨大的太空岩石撞上了水星。撞擊力大到連星球另一邊的地面都被震出皺紋。' } },
      { lat: -20, lon: 40, color: '#e0e0e0', icon: '🕳️',
        en: { kicker: 'Craters', title: 'Bumps Everywhere', question: 'Why is it so bumpy?',
          text: "Mercury has almost no air to burn up falling space rocks, and no wind or rain to smooth things over. So every crater stays there for billions of years, a lot like our Moon." },
        zh: { kicker: '隕石坑', title: '到處都是坑', question: '為什麼表面這麼坑坑洞洞？',
          text: '水星幾乎沒有空氣可以燒掉掉下來的太空岩石，也沒有風和雨把地面磨平。所以每一個坑洞都會留在那裡好幾十億年，就像我們的月球一樣。' } },
      { lat: 84, lon: 0, color: '#9ad1ff', icon: '🧊',
        en: { kicker: 'North Pole', title: 'Ice Next to the Sun', question: 'Is there really ice here?',
          text: 'Yes! Deep inside craters at the poles, sunlight never reaches the bottom. Ice has stayed frozen there, even though the daytime side of Mercury gets hot enough to melt lead.' },
        zh: { kicker: '北極', title: '太陽旁邊的冰', question: '這裡真的有冰嗎？',
          text: '有！在兩極隕石坑的深處，陽光永遠照不到底部。那裡的冰一直保持凍結，即使水星白天那一面熱到可以把鉛融化。' } },
      { lat: 0, lon: 110, color: '#ff9d42', icon: '🧲',
        en: { kicker: 'Inside', title: 'A Giant Iron Heart', question: "What's inside Mercury?",
          text: 'Mercury has a huge iron core that takes up most of the planet! Scientists think a giant crash long ago knocked away its outer rocky layers, leaving mostly the metal heart behind.' },
        zh: { kicker: '內部', title: '巨大的鐵心臟', question: '水星裡面是什麼？',
          text: '水星有一顆超大的鐵核心，占了整個星球的大部分！科學家認為很久以前一次巨大的撞擊把它外層的岩石撞掉了，只留下大部分的金屬心臟。' } }
    ],
    moons: [],
    facts: [
      { icon: '☀️', en: { title: 'Closest to the Sun', text: 'Mercury is the closest planet to the Sun. From there, the Sun would look three times bigger in the sky than it does from Earth!' }, zh: { title: '離太陽最近', text: '水星是離太陽最近的行星。從那裡看，太陽會比在地球上看起來大三倍！' } },
      { icon: '🏃', en: { title: 'A super short year', text: 'Mercury zooms around the Sun in just 88 days. That is the fastest of all the planets, which is why it was named after the speedy Roman messenger god.' }, zh: { title: '超短的一年', text: '水星只要 88 天就繞太陽一圈，是所有行星裡最快的，所以用羅馬神話裡跑得飛快的信使神來命名。' } },
      { icon: '🌡️', en: { title: 'Boiling and freezing', text: 'Daytime on Mercury reaches 430 degrees Celsius, but at night it drops to minus 180. That is the biggest temperature swing of any planet!' }, zh: { title: '又燙又冷', text: '水星白天高達攝氏 430 度，晚上卻掉到零下 180 度，是所有行星裡溫差最大的！' } },
      { icon: '📏', en: { title: 'It is shrinking', text: 'As its iron core slowly cools, Mercury is getting a tiny bit smaller. Its surface has long wrinkles, like the skin of a drying apple.' }, zh: { title: '它正在縮小', text: '隨著鐵核心慢慢冷卻，水星正在一點點變小。它的表面有長長的皺紋，就像放久了的蘋果皮。' } },
      { icon: '🌙', en: { title: 'No moons at all', text: 'Mercury has zero moons. It is so close to the Sun that the Sun\'s gravity would steal any moon away.' }, zh: { title: '一顆衛星都沒有', text: '水星沒有任何衛星。它離太陽太近了，太陽的引力會把任何衛星都搶走。' } },
      { icon: '🚀', en: { title: 'Robot visitors', text: 'Only two spacecraft have visited: Mariner 10 and MESSENGER. A new one called BepiColombo is on its way right now!' }, zh: { title: '機器人訪客', text: '只有兩艘太空船去過：水手 10 號和信使號。現在還有一艘叫「貝皮可倫坡號」正在飛過去！' } }
    ]
  },

  venus: {
    subtitle: { en: "Earth's Fiery Twin", zh: '地球的火熱雙胞胎' },
    camDist: 11,
    hotspots: [
      { lat: 20, lon: -30, color: '#ffe3b0', icon: '☁️',
        en: { kicker: 'Clouds', title: 'The Hidden Surface', question: "Why can't we see the ground?",
          text: 'Venus is wrapped in thick clouds of sulfuric acid, so nobody has ever seen its ground with their eyes. This picture shows the hidden surface, mapped by spacecraft using radar that can see through clouds.' },
        zh: { kicker: '雲層', title: '看不見的地面', question: '為什麼看不到地面？',
          text: '金星被厚厚的硫酸雲包住，從來沒有人用眼睛看過它的地面。這張圖是太空船用可以穿透雲層的雷達畫出來的隱藏地表。' } },
      { lat: -10, lon: 100, color: '#ff7a3c', icon: '🌋',
        en: { kicker: 'Volcanoes', title: 'A Planet of Volcanoes', question: 'Why are there so many volcanoes?',
          text: 'Venus has more volcanoes than any other planet, over 1,600 big ones! Its surface is young and covered in old lava. Scientists think some volcanoes may still be erupting today.' },
        zh: { kicker: '火山', title: '火山星球', question: '為什麼有這麼多火山？',
          text: '金星的火山比任何行星都多，大型的就超過 1600 座！它的地表很年輕，到處都是舊的熔岩。科學家認為有些火山到現在還在噴發。' } },
      { lat: 65, lon: 3, color: '#ffffff', icon: '⛰️',
        en: { kicker: 'Maxwell Montes', title: 'The Tallest Mountain', question: 'How high is the highest peak?',
          text: 'Maxwell Montes is about 11 kilometers high, taller than Mount Everest! Strangely, its top is coated in a shiny metal frost that "snows" out of the hot air.' },
        zh: { kicker: '麥克斯韋山', title: '最高的山', question: '最高的山有多高？',
          text: '麥克斯韋山大約 11 公里高，比聖母峰還高！奇怪的是，山頂覆蓋著一層亮亮的金屬「霜」，是從滾燙的空氣裡「下雪」下來的。' } },
      { lat: -40, lon: -120, color: '#ff5a3c', icon: '🔥',
        en: { kicker: 'Heat', title: 'The Hottest Planet', question: 'Why is Venus so hot?',
          text: 'Its thick air traps heat like a giant blanket. Venus is about 465 degrees Celsius, hotter than Mercury even though it is farther from the Sun. That is called the greenhouse effect.' },
        zh: { kicker: '高溫', title: '最熱的行星', question: '為什麼金星這麼熱？',
          text: '它厚厚的空氣像一條大棉被，把熱氣鎖在裡面。金星大約攝氏 465 度，雖然離太陽比較遠，卻比水星還熱。這就是溫室效應。' } }
    ],
    moons: [],
    facts: [
      { icon: '🔄', en: { title: 'It spins backwards', text: 'Venus spins the opposite way from most planets. On Venus, the Sun rises in the west and sets in the east!' }, zh: { title: '它是倒著轉的', text: '金星自轉的方向和大多數行星相反。在金星上，太陽是從西邊升起、東邊落下！' } },
      { icon: '⏳', en: { title: 'A day longer than a year', text: 'Venus takes 243 Earth days to spin around once, but only 225 days to go around the Sun. Its day is longer than its year!' }, zh: { title: '一天比一年還長', text: '金星自轉一圈要 243 個地球日，但繞太陽一圈只要 225 天。它的一天比一年還長！' } },
      { icon: '✨', en: { title: 'The evening star', text: 'Venus is the brightest thing in our sky after the Sun and Moon. People often call it the morning star or evening star.' }, zh: { title: '黃昏之星', text: '金星是天空中除了太陽和月亮之外最亮的東西。人們常叫它「晨星」或「昏星」。' } },
      { icon: '🏋️', en: { title: 'Crushing air', text: 'The air on Venus pushes down 90 times harder than on Earth, like being 900 meters deep in the ocean. Old spacecraft that landed there were crushed within hours.' }, zh: { title: '會壓扁人的空氣', text: '金星的空氣壓力是地球的 90 倍，像在海底 900 公尺深的地方。以前降落在那裡的太空船，幾個小時內就被壓壞了。' } },
      { icon: '🌧️', en: { title: 'Acid rain that never lands', text: 'It rains sulfuric acid on Venus, but the ground is so hot that the drops evaporate before they ever reach it.' }, zh: { title: '落不到地面的酸雨', text: '金星會下硫酸雨，但地面太熱了，雨滴還沒落地就蒸發掉了。' } },
      { icon: '💗', en: { title: 'Named for love', text: 'Venus is named after the Roman goddess of love and beauty, because it shines so beautifully in the sky.' }, zh: { title: '以愛神命名', text: '金星是用羅馬神話裡的愛與美之女神來命名的，因為它在天空中閃耀得非常美麗。' } }
    ]
  },

  earth: {
    subtitle: { en: 'Our Home', zh: '我們的家' },
    camDist: 11,
    clouds: 'textures/2k_earth_clouds.jpg',
    hotspots: [
      { lat: 0, lon: -160, color: '#5ec8ff', icon: '🌊',
        en: { kicker: 'Pacific Ocean', title: 'The Blue Planet', question: 'Why is Earth so blue?',
          text: 'About 71 percent of Earth is covered in water! The Pacific Ocean alone is bigger than all the land on Earth put together. Earth is the only planet we know with liquid water on its surface.' },
        zh: { kicker: '太平洋', title: '藍色星球', question: '為什麼地球這麼藍？',
          text: '地球大約有 71% 被水覆蓋！光是太平洋就比地球上所有陸地加起來還大。地球是我們知道唯一表面有液態水的行星。' } },
      { lat: 23, lon: 10, color: '#ffd28a', icon: '🏜️',
        en: { kicker: 'Sahara', title: 'The Great Desert', question: "What's the big yellow area?",
          text: 'That is the Sahara, the biggest hot desert in the world, about as big as the United States. Its dust blows all the way across the ocean and helps feed the Amazon rainforest!' },
        zh: { kicker: '撒哈拉', title: '大沙漠', question: '那一大片黃色是什麼？',
          text: '那是撒哈拉沙漠，世界上最大的炎熱沙漠，大約和美國一樣大。它的沙塵會飄過整個大西洋，幫忙滋養亞馬遜雨林！' } },
      { lat: -5, lon: -62, color: '#7dff9a', icon: '🌳',
        en: { kicker: 'Amazon', title: 'The Green Lungs', question: "What's the green?",
          text: 'Forests! The Amazon is the biggest rainforest on Earth. About one in ten of all the animal and plant species on the planet live there.' },
        zh: { kicker: '亞馬遜', title: '綠色的肺', question: '綠色的是什麼？',
          text: '是森林！亞馬遜是地球上最大的雨林。地球上每十種動植物，就有一種住在那裡。' } },
      { lat: -84, lon: 0, color: '#ffffff', icon: '🐧',
        en: { kicker: 'Antarctica', title: 'The Frozen Bottom', question: "What's the white at the bottom?",
          text: 'Antarctica! It is covered in ice up to 4 kilometers thick and holds about 70 percent of all the fresh water on Earth. Nobody lives there except visiting scientists and lots of penguins.' },
        zh: { kicker: '南極洲', title: '冰凍的底部', question: '底下白白的是什麼？',
          text: '是南極洲！它被厚達 4 公里的冰覆蓋，儲存了地球大約 70% 的淡水。那裡沒有人長住，只有來做研究的科學家和很多企鵝。' } },
      { lat: 28, lon: 87, color: '#c9b8ff', icon: '🏔️',
        en: { kicker: 'Himalayas', title: 'The Roof of the World', question: "Where's the highest place?",
          text: 'Mount Everest, in the Himalayas, is 8,849 meters tall. These mountains are still growing a few millimeters every year, because India is slowly pushing into Asia!' },
        zh: { kicker: '喜馬拉雅山', title: '世界屋脊', question: '最高的地方在哪裡？',
          text: '喜馬拉雅山的聖母峰有 8849 公尺高。這些山每年還在長高幾公釐，因為印度正慢慢地擠進亞洲！' } }
    ],
    moons: [
      { key: 'moon', tex: 'textures/2k_moon.jpg', dist: 8.5, speed: 0.9, size: 0.95, icon: '🌕',
        en: { name: 'The Moon', subtitle: 'Our Only Moon', text: 'The Moon is slowly drifting away from us, about 4 centimeters every year. Its gravity pulls on our oceans and makes the tides. Twelve people have walked on it!' },
        zh: { name: '月球', subtitle: '我們唯一的衛星', text: '月球正慢慢離我們而去，每年大約遠離 4 公分。它的引力會拉動海水，形成潮汐。已經有十二個人在上面走過！' } }
    ],
    facts: [
      { icon: '🧬', en: { title: 'The only home for life', text: 'Earth is the only place in the universe where we know life exists. Every animal, plant and person we know of lives here.' }, zh: { title: '唯一有生命的家', text: '地球是宇宙中我們唯一確定有生命的地方。我們認識的每一種動物、植物和每一個人都住在這裡。' } },
      { icon: '🍊', en: { title: 'Not a perfect ball', text: 'Earth spins so fast that it bulges out a little at the middle. It is about 43 kilometers wider around the equator than from pole to pole.' }, zh: { title: '不是完美的圓球', text: '地球轉得很快，所以中間有點鼓起來。赤道那一圈比從北極到南極寬了大約 43 公里。' } },
      { icon: '🛡️', en: { title: 'An invisible shield', text: 'Deep inside, spinning liquid iron makes a magnetic field around Earth. It protects us from dangerous particles from the Sun, and makes the northern lights glow.' }, zh: { title: '看不見的盾牌', text: '地球深處旋轉的液態鐵製造出磁場，包住整個地球。它保護我們不受太陽危險粒子的傷害，還會讓極光發亮。' } },
      { icon: '💨', en: { title: 'Racing through space', text: 'Right now you are moving at about 107,000 kilometers per hour as Earth zooms around the Sun. You cannot feel it because everything moves together.' }, zh: { title: '在太空中飛奔', text: '此刻的你正以每小時大約 10 萬 7 千公里的速度跟著地球繞太陽飛。你感覺不到，是因為所有東西都一起在動。' } },
      { icon: '🕰️', en: { title: 'Days are getting longer', text: 'The Moon slowly makes Earth spin a tiny bit slower. Every hundred years, a day gets about two milliseconds longer. When dinosaurs lived, a day was only 23 hours!' }, zh: { title: '一天越來越長', text: '月球讓地球的自轉慢慢變慢。每一百年，一天會變長大約兩毫秒。恐龍還在的時候，一天只有 23 小時！' } },
      { icon: '🎂', en: { title: 'Four and a half billion years old', text: 'Earth formed about 4.5 billion years ago from dust and rocks swirling around the young Sun. The oldest rocks we have found are almost that old.' }, zh: { title: '四十五億歲', text: '地球大約在 45 億年前，由繞著年輕太陽打轉的塵埃和岩石聚集而成。我們找到最古老的岩石差不多就有這麼老。' } }
    ]
  },

  mars: {
    subtitle: { en: 'The Red Planet', zh: '紅色星球' },
    camDist: 11,
    hotspots: [
      { lat: 18, lon: -134, color: '#ff9d42', icon: '🌋',
        en: { kicker: 'Olympus Mons', title: 'The Biggest Volcano', question: "What's the biggest volcano?",
          text: 'Olympus Mons is the tallest volcano in the whole solar system, almost three times higher than Mount Everest! It is so wide that it would cover the entire country of France.' },
        zh: { kicker: '奧林帕斯山', title: '最大的火山', question: '最大的火山有多大？',
          text: '奧林帕斯山是全太陽系最高的火山，幾乎是聖母峰的三倍高！它寬到可以把整個法國蓋住。' } },
      { lat: -12, lon: -70, color: '#ffd28a', icon: '🏞️',
        en: { kicker: 'Valles Marineris', title: 'The Giant Scratch', question: "What's that giant scratch?",
          text: 'That is Valles Marineris, a canyon 4,000 kilometers long and 7 kilometers deep. It would stretch all the way across the United States. The Grand Canyon would be just a tiny side branch!' },
        zh: { kicker: '水手谷', title: '巨大的刮痕', question: '那條大刮痕是什麼？',
          text: '那是水手谷，一條 4000 公里長、7 公里深的大峽谷，可以從美國的東岸一直延伸到西岸。美國大峽谷跟它比起來只是一條小小的支流！' } },
      { lat: 84, lon: 0, color: '#ffffff', icon: '❄️',
        en: { kicker: 'North Pole', title: 'Ice Caps', question: 'Is there ice on Mars?',
          text: 'Yes! Both poles have ice caps made of water ice and frozen carbon dioxide, which we call dry ice. The caps grow bigger in winter and shrink in summer, just like on Earth.' },
        zh: { kicker: '北極', title: '極冠', question: '火星上有冰嗎？',
          text: '有！兩極都有由水冰和乾冰（凍結的二氧化碳）組成的極冠。極冠在冬天變大、夏天縮小，和地球一樣。' } },
      { lat: -30, lon: 60, color: '#ff5a3c', icon: '🟥',
        en: { kicker: 'Red Dust', title: 'Why So Red?', question: 'Why is Mars red?',
          text: 'The soil on Mars is full of iron that rusted long ago, so the whole planet is covered in reddish dust. Sometimes huge dust storms wrap around the entire planet for months!' },
        zh: { kicker: '紅色沙塵', title: '為什麼這麼紅？', question: '火星為什麼是紅色的？',
          text: '火星的土壤裡有很多很久以前就生鏽的鐵，所以整個星球都蓋著紅色的沙塵。有時候巨大的沙塵暴會把整個星球包起來好幾個月！' } }
    ],
    moons: [
      { key: 'phobos', tex: 'textures/moon_phobos.jpg', dist: 6.6, speed: 2.0, size: 0.32, squash: true, icon: '🥔',
        en: { name: 'Phobos', subtitle: 'The Potato Moon', text: 'Phobos is a lumpy, potato-shaped moon only 22 kilometers across. It is spiraling closer to Mars every year and will break apart in about 50 million years, maybe forming a ring!' },
        zh: { name: '火衛一', subtitle: '馬鈴薯衛星', text: '火衛一是一顆凹凸不平、像馬鈴薯的衛星，只有 22 公里寬。它每年都更靠近火星一點，大約五千萬年後會碎掉，說不定會變成一圈環！' } },
      { key: 'deimos', style: 'cratered', color: '#8b8378', spots: '#4f4a42', dist: 9.0, speed: 1.1, size: 0.22, squash: true, icon: '🪨',
        en: { name: 'Deimos', subtitle: 'The Tiny Moon', text: 'Deimos is even smaller than Phobos, only about 12 kilometers across. From Mars, it would look like a bright star slowly crossing the sky.' },
        zh: { name: '火衛二', subtitle: '迷你衛星', text: '火衛二比火衛一還小，只有大約 12 公里寬。從火星上看，它就像一顆慢慢劃過天空的亮星。' } }
    ],
    facts: [
      { icon: '🤖', en: { title: 'Robots live there', text: 'Right now, rovers named Curiosity and Perseverance are driving around on Mars, taking pictures and studying rocks. A little helicopter called Ingenuity even flew there!' }, zh: { title: '機器人住在那裡', text: '現在，叫好奇號和毅力號的探測車正在火星上開來開去，拍照片、研究石頭。一台叫機智號的小直升機還在那裡飛過！' } },
      { icon: '🦘', en: { title: 'Jump three times higher', text: 'Gravity on Mars is only about one third of Earth\'s. You could jump three times higher there, and everything would feel much lighter.' }, zh: { title: '可以跳三倍高', text: '火星的重力只有地球的三分之一。在那裡你可以跳三倍高，所有東西都會感覺輕很多。' } },
      { icon: '🌅', en: { title: 'Blue sunsets', text: 'On Mars, the sky is butterscotch-colored in the day, but sunsets are blue! The fine dust scatters light the opposite way from Earth.' }, zh: { title: '藍色的夕陽', text: '在火星上，白天的天空是奶油糖色的，但夕陽是藍色的！細細的沙塵把光線散射的方式剛好和地球相反。' } },
      { icon: '🏞️', en: { title: 'It once had rivers', text: 'Long ago, Mars had rivers, lakes and maybe even an ocean. We can still see the dried-up riverbeds. Scientists are searching for signs of ancient life.' }, zh: { title: '以前有河流', text: '很久以前，火星有河流、湖泊，說不定還有海洋。我們現在還能看到乾掉的河床。科學家正在尋找古代生命的痕跡。' } },
      { icon: '📅', en: { title: 'A day almost like ours', text: 'A day on Mars lasts 24 hours and 37 minutes, very close to Earth. But a year takes 687 days, almost twice as long as ours.' }, zh: { title: '一天和地球差不多', text: '火星上的一天是 24 小時 37 分鐘，和地球很接近。但它的一年要 687 天，幾乎是地球的兩倍長。' } },
      { icon: '🌪️', en: { title: 'Dust devils', text: 'Mars has spinning towers of dust called dust devils that can be 10 times taller than the ones on Earth. Rovers have taken pictures of them dancing across the plains.' }, zh: { title: '塵捲風', text: '火星上有旋轉的沙塵柱叫「塵捲風」，可以比地球上的高十倍。探測車拍到它們在平原上跳舞的樣子。' } }
    ]
  },

  jupiter: {
    subtitle: { en: 'King of the Planets', zh: '行星之王' },
    camDist: 11,
    hotspots: [
      { lat: -22, lon: -48, color: '#ff5a3c', icon: '🔴',
        en: { kicker: 'Great Red Spot', title: 'The Great Red Spot', question: 'Why is there a Great Red Spot?',
          text: "It's a giant storm — bigger than the whole planet Earth! Winds swirl around it for hundreds of years, and scientists are still watching it change shape." },
        zh: { kicker: '大紅斑', title: '大紅斑', question: '為什麼會有大紅斑？',
          text: '它其實是一個超級大的暴風，比整個地球還要大！裡面的風已經旋轉了好幾百年，科學家到現在還在觀察它慢慢改變形狀。' } },
      { lat: 12, lon: 95, color: '#ff9d42', icon: '🟠',
        en: { kicker: 'Cloud Bands', title: 'The Orange Bands', question: 'What is the orange stuff?',
          text: 'Those are clouds made of ammonia and sulfur, stretched into stripes by super-fast winds. Some winds on Jupiter blow faster than six hundred kilometers per hour!' },
        zh: { kicker: '雲帶', title: '橘色的條紋', question: '橘色的東西是什麼？',
          text: '那些是由氨和硫化物組成的雲，被超級快的風吹成一條一條的。木星上有些風的速度超過每小時六百公里！' } },
      { lat: 38, lon: -125, color: '#eaf2ff', icon: '⚪',
        en: { kicker: 'Cloud Zones', title: 'The White Zones', question: 'What is the white stuff?',
          text: 'Those bright bands are icy ammonia clouds, floating higher and colder than the orange bands. Jupiter has no solid ground at all — it is clouds all the way down.' },
        zh: { kicker: '雲區', title: '白色的區域', question: '白色的東西是什麼？',
          text: '那些明亮的帶子是冰冷的氨結晶雲，飄在比橘色雲帶更高、更冷的地方。木星完全沒有堅硬的地面，往下全部都是雲！' } },
      { lat: -41, lon: 60, color: '#ffffff', icon: '🫧',
        en: { kicker: 'String of Pearls', title: 'The String of Pearls', question: 'What are those white ovals?',
          text: 'Those white ovals are a row of huge storms nicknamed the String of Pearls! Each one is a swirling cyclone big enough to swallow a whole country.' },
        zh: { kicker: '珍珠串', title: '珍珠串暴風', question: '那些白色的橢圓是什麼？',
          text: '那些白色的橢圓是一排巨大的暴風，暱稱叫「珍珠串」！每一顆都是一個旋轉的氣旋，大到可以吞下一整個國家。' } },
      { lat: 80, lon: 0, color: '#7dffd8', icon: '🌌',
        en: { kicker: 'North Pole', title: "Jupiter's Northern Lights", question: 'Why do the poles glow?',
          text: 'Jupiter has the biggest auroras in the whole solar system! Its super-strong magnetic field grabs tiny particles from space and from its volcanic moon Io, and makes them glow around the poles.' },
        zh: { kicker: '北極', title: '木星的極光', question: '為什麼兩極會發光？',
          text: '木星擁有全太陽系最大的極光！它超強的磁場會抓住來自太空和火山衛星埃歐的微小粒子，讓它們在兩極周圍發光。' } },
      { lat: 2, lon: 150, color: '#c9b8ff', icon: '💫',
        en: { kicker: 'Faint Rings', title: "Jupiter's Hidden Rings", question: 'Why does it have rings?',
          text: "Jupiter actually has faint dusty rings! They're made from tiny bits of rock kicked up by meteors hitting its small inner moons. They're so faint that nobody noticed them until a spacecraft flew by in 1979." },
        zh: { kicker: '微弱的環', title: '木星隱藏的環', question: '為什麼會有環？',
          text: '木星其實也有很淡的塵埃環！它們是流星撞擊木星內側的小衛星時，濺起來的小碎屑組成的。因為太淡了，直到 1979 年太空船飛過才被發現。' } },
      { lat: -50, lon: 20, color: '#9ad1ff', icon: '🌙',
        en: { kicker: 'Moon System', title: 'So Many Moons!', question: 'Why does it have so many moons?',
          text: 'Jupiter is so big and heavy that its gravity easily captures passing space rocks and ice! It has over ninety moons, more than any other planet. Look around Jupiter and tap a moon to meet it.' },
        zh: { kicker: '衛星系統', title: '好多好多衛星！', question: '為什麼有這麼多衛星？',
          text: '木星又大又重，它的引力很容易就把經過的太空岩石和冰塊抓過來！它有超過九十顆衛星，比太陽系任何行星都多。看看木星旁邊，點一顆衛星認識它吧！' } }
    ],
    moons: [
      { key: 'io', tex: 'textures/moon_io.jpg', dist: 6.2, speed: 1.6, size: 0.42, icon: '🌋',
        en: { name: 'Io', subtitle: 'The Volcano Moon', text: 'Jupiter squeezes and stretches Io so hard that it melts rock inside! Io shoots fiery volcanoes into space, making it the most volcanic place in the whole solar system. Its yellow colour comes from sulfur.' },
        zh: { name: '埃歐', subtitle: '火山衛星', text: '木星用力擠壓、拉扯埃歐，把它裡面的岩石都融化了！埃歐會把熾熱的火山噴到太空中，是全太陽系火山最多的地方。它的黃色來自硫磺。' } },
      { key: 'europa', tex: 'textures/moon_europa.jpg', dist: 7.6, speed: 1.25, size: 0.38, icon: '🧊',
        en: { name: 'Europa', subtitle: 'The Ocean Moon', text: 'Under its icy, cracked shell, Europa may hide a giant ocean with more water than every ocean on Earth combined! Scientists think it could even be a home for tiny forms of life.' },
        zh: { name: '歐羅巴', subtitle: '海洋衛星', text: '在冰冷、布滿裂痕的外殼底下，歐羅巴可能藏著一片大海，水量比地球所有海洋加起來還多！科學家認為那裡甚至可能住著小小的生命。' } },
      { key: 'ganymede', tex: 'textures/moon_ganymede.jpg', dist: 9.2, speed: 0.95, size: 0.5, icon: '🪨',
        en: { name: 'Ganymede', subtitle: 'The Giant Moon', text: "Ganymede is the biggest moon in the whole solar system, even bigger than the planet Mercury! It's the only moon we know that makes its own magnetic field." },
        zh: { name: '蓋尼米德', subtitle: '巨大衛星', text: '蓋尼米德是全太陽系最大的衛星，甚至比水星還大！它是我們目前知道唯一會自己製造磁場的衛星。' } },
      { key: 'callisto', tex: 'textures/moon_callisto.jpg', dist: 10.8, speed: 0.7, size: 0.46, icon: '🕳️',
        en: { name: 'Callisto', subtitle: 'The Crater Moon', text: "Callisto's surface is covered in billions of years of craters from space rocks crashing into it. It's one of the oldest, most battered surfaces we've ever seen!" },
        zh: { name: '卡利斯多', subtitle: '隕石坑衛星', text: '卡利斯多的表面布滿了幾十億年來太空岩石撞出來的坑洞。它是我們見過最古老、傷痕最多的表面之一！' } }
    ],
    facts: [
      { icon: '🌍', en: { title: '1,300 Earths could fit inside', text: 'Jupiter is so enormous that about one thousand three hundred planet Earths could fit inside it!' }, zh: { title: '可以裝下 1300 顆地球', text: '木星大到可以裝下大約一千三百顆地球！' } },
      { icon: '⏱️', en: { title: 'The fastest spinner', text: 'A day on Jupiter lasts only about ten hours. It spins so fast that it bulges out in the middle, like a slightly squashed ball!' }, zh: { title: '轉得最快的行星', text: '木星上的一天只有大約十小時。它轉得太快了，中間都被甩得鼓起來，像一顆被輕輕壓扁的球！' } },
      { icon: '⭐', en: { title: 'Almost a star', text: 'Jupiter is made of the same gases as the Sun: hydrogen and helium. If it were about eighty times heavier, it could have become a star!' }, zh: { title: '差一點變成星星', text: '木星和太陽是用同樣的氣體做成的：氫和氦。如果它再重八十倍，就可能變成一顆星星！' } },
      { icon: '⚡', en: { title: 'Super lightning', text: 'Jupiter has lightning storms too, and its bolts can be a thousand times more powerful than lightning on Earth!' }, zh: { title: '超級閃電', text: '木星也會打雷閃電，而且威力可以比地球的閃電強上一千倍！' } },
      { icon: '🧲', en: { title: 'A giant magnet', text: "Jupiter has the strongest magnetic field of any planet, about twenty thousand times stronger than Earth's. It makes glowing auroras at the poles that are bigger than our whole planet!" }, zh: { title: '一塊超大磁鐵', text: '木星是太陽系裡最強的大磁鐵，磁場比地球強大約兩萬倍，還會在南北極製造出比整個地球還大的極光！' } },
      { icon: '🛡️', en: { title: "Earth's bodyguard", text: "Jupiter's strong gravity pulls in many comets and asteroids, so fewer of them crash into Earth. Thanks, Jupiter!" }, zh: { title: '地球的保鑣', text: '木星強大的引力會把很多彗星和小行星吸過去，讓它們比較不會撞到地球。謝謝你，木星！' } },
      { icon: '🚀', en: { title: 'A robot visitor', text: "NASA's Juno spacecraft has been flying around Jupiter since 2016, taking amazing close-up pictures of its storms and poles." }, zh: { title: '機器人訪客', text: 'NASA 的朱諾號太空船從 2016 年開始繞著木星飛，拍下許多超近距離的暴風和極地照片。' } },
      { icon: '🌗', en: { title: 'No ground to land on', text: "You could never land on Jupiter! There's no surface to stand on. The deeper you go, the gases get squeezed so hard they turn into a strange liquid metal." }, zh: { title: '沒有地面可以降落', text: '你永遠沒辦法降落在木星上！它沒有可以站的地面。越往裡面走，氣體被壓得越緊，最後會變成一種奇怪的液態金屬。' } },
      { icon: '🔭', en: { title: 'Watched for thousands of years', text: 'Jupiter is so bright you can see it with your own eyes at night. People have watched it for thousands of years, and Galileo found its four big moons with a telescope in 1610.' }, zh: { title: '人類看了好幾千年', text: '木星非常明亮，晚上用肉眼就看得到。人類已經觀察它好幾千年了，伽利略在 1610 年用望遠鏡發現了它的四顆大衛星。' } },
      { icon: '📏', en: { title: 'A very long year', text: 'Jupiter is so far from the Sun that one trip around it — one Jupiter year — takes almost twelve Earth years!' }, zh: { title: '超級長的一年', text: '木星離太陽很遠，繞太陽一圈（也就是木星的一年）要花將近十二個地球年！' } }
    ]
  },

  saturn: {
    subtitle: { en: 'The Ringed Wonder', zh: '戴著光環的奇蹟' },
    camDist: 17,
    rings: { tex: 'textures/2k_saturn_ring_alpha.png', inner: 1.35, outer: 2.3, tilt: 0.45, opacity: 0.9 },
    hotspots: [
      { ring: true, color: '#ffe9b0', icon: '💍',
        en: { kicker: 'The Rings', title: 'Rings of Ice', question: 'What are the rings made of?',
          text: 'Billions of chunks of ice and rock, from tiny grains of dust to pieces as big as a house! The rings stretch 280,000 kilometers across, but most of them are only about 10 meters thick, thinner than a sheet of paper compared to their size.' },
        zh: { kicker: '土星環', title: '冰做的環', question: '土星環是什麼做的？',
          text: '是幾十億塊冰和岩石，小的像沙塵，大的像一棟房子！土星環寬達 28 萬公里，但大部分只有大約 10 公尺厚，以它的大小來說比一張紙還薄。' } },
      { lat: 84, lon: 0, color: '#7dffd8', icon: '⬡',
        en: { kicker: 'North Pole', title: 'The Hexagon', question: "What's the shape at the north pole?",
          text: 'There is a giant six-sided storm at the north pole, bigger than the whole Earth! Scientists still do not fully understand why it makes a hexagon instead of a circle.' },
        zh: { kicker: '北極', title: '六邊形風暴', question: '北極那個形狀是什麼？',
          text: '北極有一個巨大的六邊形風暴，比整個地球還大！科學家到現在還不完全明白，為什麼它是六邊形而不是圓形。' } },
      { lat: 20, lon: 60, color: '#ffd28a', icon: '🟡',
        en: { kicker: 'Cloud Bands', title: 'Soft Golden Stripes', question: 'Why are the stripes so faint?',
          text: 'Saturn has stripes just like Jupiter, but a hazy layer of ammonia clouds floats high above them and softens the colors, like looking through fog.' },
        zh: { kicker: '雲帶', title: '柔和的金色條紋', question: '為什麼條紋這麼淡？',
          text: '土星和木星一樣有條紋，但有一層朦朧的氨雲飄在高處，把顏色蓋得柔柔的，像隔著一層霧在看。' } },
      { lat: -30, lon: -100, color: '#ffffff', icon: '⛈️',
        en: { kicker: 'Storms', title: 'The Great White Spot', question: 'Does Saturn have storms?',
          text: 'Yes! About every 30 years a huge storm called the Great White Spot appears and wraps all the way around the planet. Winds on Saturn can reach 1,800 kilometers per hour!' },
        zh: { kicker: '風暴', title: '大白斑', question: '土星有風暴嗎？',
          text: '有！大約每 30 年會出現一個叫「大白斑」的巨大風暴，把整個星球繞一圈。土星上的風速可以達到每小時 1800 公里！' } }
    ],
    moons: [
      { key: 'titan', tex: 'textures/moon_titan.jpg', dist: 12.5, speed: 0.8, size: 0.6, icon: '🟠',
        en: { name: 'Titan', subtitle: 'The Moon with Air', text: 'Titan is bigger than the planet Mercury and is the only moon with thick air. It has rivers and lakes, but they are made of liquid methane, not water. Its orange sky is full of haze.' },
        zh: { name: '泰坦', subtitle: '有空氣的衛星', text: '泰坦比水星還大，是唯一有濃厚大氣的衛星。它有河流和湖泊，但裡面裝的是液態甲烷，不是水。它的橘色天空充滿了霧霾。' } },
      { key: 'enceladus', tex: 'textures/moon_enceladus.jpg', dist: 10.4, speed: 1.4, size: 0.32, icon: '💦',
        en: { name: 'Enceladus', subtitle: 'The Geyser Moon', text: 'Tiny Enceladus shoots huge fountains of water into space from cracks near its south pole! Under its bright icy shell there is a salty ocean, one of the best places to look for life.' },
        zh: { name: '恩克拉多斯', subtitle: '噴泉衛星', text: '小小的恩克拉多斯會從南極附近的裂縫，把巨大的水柱噴到太空中！在它明亮的冰殼底下有一片鹹鹹的海洋，是尋找生命最棒的地方之一。' } }
    ],
    facts: [
      { icon: '🛁', en: { title: 'It could float', text: 'Saturn is so light for its size that if you had a bathtub big enough, it would float in the water!' }, zh: { title: '它會浮在水上', text: '土星以它的大小來說非常輕，如果有一個夠大的浴缸，它會浮在水面上！' } },
      { icon: '🌙', en: { title: 'The moon champion', text: 'Saturn has 146 known moons, more than any other planet. New ones are still being discovered!' }, zh: { title: '衛星冠軍', text: '土星已知有 146 顆衛星，比任何行星都多，而且還在不斷發現新的！' } },
      { icon: '👂', en: { title: 'Galileo thought it had ears', text: 'When Galileo first saw Saturn through his small telescope in 1610, the rings looked like two bumps. He thought Saturn had ears!' }, zh: { title: '伽利略以為它有耳朵', text: '1610 年伽利略第一次用小望遠鏡看土星時，土星環看起來像兩個凸起。他還以為土星長了耳朵！' } },
      { icon: '⏱️', en: { title: 'Short days, long years', text: 'A day on Saturn is only about 10 and a half hours, but one year takes 29 and a half Earth years.' }, zh: { title: '短短的一天，長長的一年', text: '土星的一天只有大約 10 個半小時，但一年要 29 個半地球年。' } },
      { icon: '🛰️', en: { title: 'Cassini the explorer', text: 'The Cassini spacecraft circled Saturn for 13 years, then dove into the planet on purpose in 2017 so it would never crash into a moon that might have life.' }, zh: { title: '探險家卡西尼號', text: '卡西尼號太空船繞了土星 13 年，2017 年故意衝進土星裡結束任務，這樣它才永遠不會撞到可能有生命的衛星。' } },
      { icon: '⌛', en: { title: 'The rings are disappearing', text: 'The rings are slowly raining down onto Saturn. In about 100 million years they may be gone, so we are lucky to see them now!' }, zh: { title: '土星環正在消失', text: '土星環正慢慢像雨一樣掉進土星裡。大約一億年後可能就沒有了，所以我們現在能看到真的很幸運！' } }
    ]
  },

  uranus: {
    subtitle: { en: 'The Sideways Planet', zh: '躺著轉的行星' },
    camDist: 13,
    axisTilt: { x: 0.15, y: 0.75, z: 1.6 },
    rings: { color: '#c8d8e8', inner: 1.55, outer: 1.95, tilt: 0, opacity: 0.35 },
    hotspots: [
      { lat: 5, lon: 0, color: '#9af5ff', icon: '🩵',
        en: { kicker: 'Color', title: 'Blue-Green Fog', question: 'Why is Uranus blue-green?',
          text: 'The air on Uranus has a gas called methane. Methane soaks up red light and bounces back blue and green, so the whole planet looks like a smooth blue-green marble.' },
        zh: { kicker: '顏色', title: '藍綠色的霧', question: '天王星為什麼是藍綠色？',
          text: '天王星的空氣裡有一種叫甲烷的氣體。甲烷會吸收紅色的光，把藍色和綠色反射回來，所以整個星球看起來像一顆光滑的藍綠色彈珠。' } },
      { lat: 84, lon: 0, color: '#ffffff', icon: '🔄',
        en: { kicker: 'The Pole', title: 'Spinning on Its Side', question: 'Why does it spin on its side?',
          text: 'Uranus is tipped over by 98 degrees, so it rolls around the Sun like a ball instead of spinning like a top! Scientists think something as big as Earth crashed into it long ago. Each pole gets 42 years of daylight, then 42 years of night.' },
        zh: { kicker: '極點', title: '側躺著轉', question: '為什麼它是躺著轉的？',
          text: '天王星傾斜了 98 度，所以它像一顆球在地上滾一樣繞著太陽，而不是像陀螺一樣轉！科學家認為很久以前有一顆和地球一樣大的東西撞上了它。它的每一個極點會先有 42 年的白天，再有 42 年的黑夜。' } },
      { lat: -40, lon: 100, color: '#c9e8ff', icon: '🥶',
        en: { kicker: 'Temperature', title: 'The Coldest Planet', question: 'Is it the coldest?',
          text: 'Yes! Uranus can get down to minus 224 degrees Celsius, colder than Neptune even though Neptune is farther from the Sun. Scientists are not sure why it lets out so little heat.' },
        zh: { kicker: '溫度', title: '最冷的行星', question: '它是最冷的嗎？',
          text: '對！天王星可以冷到零下 224 度，比海王星還冷，雖然海王星離太陽更遠。科學家還不確定為什麼它放出的熱這麼少。' } },
      { ring: true, color: '#e8f0ff', icon: '💫',
        en: { kicker: 'Rings', title: 'Thin Dark Rings', question: 'Does Uranus have rings?',
          text: 'Yes, 13 thin, dark rings! They were found by accident in 1977 when a star blinked several times as Uranus passed in front of it. Because the planet is tipped over, the rings go up and down instead of side to side.' },
        zh: { kicker: '環', title: '細細的黑環', question: '天王星有環嗎？',
          text: '有，13 條又細又黑的環！它們是 1977 年意外發現的，當時天王星從一顆星星前面經過，那顆星星閃了好幾下。因為天王星是躺著的，它的環是上下直立的，不是橫的。' } }
    ],
    moons: [
      { key: 'titania', style: 'rocky', color: '#a39e96', spots: '#5f5a54', dist: 9.0, speed: 0.9, size: 0.4, icon: '🌑',
        en: { name: 'Titania', subtitle: 'The Biggest Moon of Uranus', text: 'Titania is about half the size of our Moon. It has huge canyons that cracked open when the icy inside froze and expanded, like a frozen water bottle.' },
        zh: { name: '天衛三', subtitle: '天王星最大的衛星', text: '天衛三大約是月球的一半大。它有巨大的峽谷，是內部的冰凍結膨脹時裂開的，就像結冰的水瓶會裂開一樣。' } },
      { key: 'miranda', style: 'icy', color: '#d5d5d5', spots: '#8c8c8c', dist: 6.8, speed: 1.5, size: 0.28, icon: '🧩',
        en: { name: 'Miranda', subtitle: 'The Patchwork Moon', text: 'Miranda looks like it was smashed apart and put back together wrong! It has the tallest cliff in the solar system, 20 kilometers high. If you jumped off, it would take 10 minutes to reach the bottom.' },
        zh: { name: '天衛五', subtitle: '拼布衛星', text: '天衛五看起來像是被撞碎後又亂拼回去的！它有全太陽系最高的懸崖，高達 20 公里。如果從上面跳下去，要 10 分鐘才會落到底。' } }
    ],
    facts: [
      { icon: '🔭', en: { title: 'Found with a telescope', text: 'Uranus was the first planet discovered with a telescope, by William Herschel in 1781. Before that, people thought it was just a faint star.' }, zh: { title: '用望遠鏡發現的', text: '天王星是第一顆用望遠鏡發現的行星，1781 年由威廉·赫歇爾找到。在那之前，大家以為它只是一顆暗暗的星星。' } },
      { icon: '🎭', en: { title: 'Moons named after Shakespeare', text: 'Uranus has 28 known moons, and most are named after characters from Shakespeare plays, like Titania, Oberon and Puck.' }, zh: { title: '以莎士比亞角色命名的衛星', text: '天王星已知有 28 顆衛星，大多用莎士比亞戲劇的角色命名，像泰坦妮亞、奧伯龍和帕克。' } },
      { icon: '💎', en: { title: 'Diamond rain', text: 'Deep inside Uranus, the pressure is so strong that scientists think carbon gets squeezed into diamonds that fall like rain!' }, zh: { title: '鑽石雨', text: '在天王星深處，壓力大到科學家認為碳會被擠壓成鑽石，像雨一樣往下掉！' } },
      { icon: '📅', en: { title: 'An 84-year journey', text: 'One year on Uranus lasts 84 Earth years. Most people would only see one Uranus birthday in their whole life.' }, zh: { title: '84 年的旅程', text: '天王星的一年是 84 個地球年。大多數人一輩子只能過一次天王星生日。' } },
      { icon: '🛰️', en: { title: 'Only one visitor', text: 'Only one spacecraft, Voyager 2, has ever flown past Uranus, back in 1986. Almost everything we know comes from that one quick visit.' }, zh: { title: '只有一位訪客', text: '只有一艘太空船「航海家 2 號」在 1986 年飛過天王星。我們知道的大部分事情都來自那一次短短的拜訪。' } },
      { icon: '🏛️', en: { title: 'Named after the sky', text: 'Uranus is the only planet named after a Greek god instead of a Roman one. Uranus was the ancient god of the sky.' }, zh: { title: '以天空之神命名', text: '天王星是唯一用希臘神而不是羅馬神命名的行星。烏拉諾斯是古代的天空之神。' } }
    ]
  },

  neptune: {
    subtitle: { en: 'The Windy Blue Giant', zh: '狂風的藍色巨人' },
    camDist: 11,
    hotspots: [
      { lat: -22, lon: -40, color: '#3d6bff', icon: '🌀',
        en: { kicker: 'Great Dark Spot', title: 'The Dark Storm', question: 'Does Neptune have a spot too?',
          text: 'Yes! When Voyager 2 flew past in 1989 it saw a Great Dark Spot, a storm as big as Earth. A few years later it vanished, but new dark spots keep appearing and disappearing.' },
        zh: { kicker: '大黑斑', title: '黑色風暴', question: '海王星也有斑點嗎？',
          text: '有！1989 年航海家 2 號飛過時，看到一個和地球一樣大的「大黑斑」風暴。幾年後它消失了，但新的黑斑一直在出現又不見。' } },
      { lat: 30, lon: 90, color: '#ffffff', icon: '💨',
        en: { kicker: 'Winds', title: 'The Windiest Place', question: 'How windy is it?',
          text: 'Neptune has the fastest winds in the whole solar system, over 2,000 kilometers per hour! That is faster than a jet plane. The bright white streaks are high, fast-moving clouds.' },
        zh: { kicker: '風', title: '最多風的地方', question: '風有多大？',
          text: '海王星有全太陽系最快的風，超過每小時 2000 公里！比噴射機還快。那些亮白色的條紋是飄得很高、跑得很快的雲。' } },
      { lat: 0, lon: 160, color: '#5ec8ff', icon: '💙',
        en: { kicker: 'Color', title: 'Deep Blue', question: 'Why is it so blue?',
          text: 'Like Uranus, Neptune has methane in its air that soaks up red light. But Neptune is a much deeper blue, and scientists still are not sure what extra ingredient makes it so vivid.' },
        zh: { kicker: '顏色', title: '深藍色', question: '為什麼這麼藍？',
          text: '和天王星一樣，海王星的空氣裡有會吸收紅光的甲烷。但海王星的藍色深很多，科學家還不確定是什麼額外的成分讓它這麼鮮豔。' } },
      { lat: -60, lon: 20, color: '#c9b8ff', icon: '🔦',
        en: { kicker: 'Distance', title: 'Far, Far Away', question: 'How far away is Neptune?',
          text: 'Neptune is about 4.5 billion kilometers from the Sun. Sunlight takes over 4 hours to get there, and it is 900 times dimmer than on Earth. Noon on Neptune looks like twilight.' },
        zh: { kicker: '距離', title: '好遠好遠', question: '海王星有多遠？',
          text: '海王星離太陽大約 45 億公里。陽光要飛 4 個多小時才到得了，而且比地球上暗 900 倍。海王星的正中午看起來就像黃昏。' } }
    ],
    moons: [
      { key: 'triton', tex: 'textures/moon_triton.jpg', dist: 8.5, speed: 1.0, size: 0.5, icon: '🧊',
        en: { name: 'Triton', subtitle: 'The Backwards Moon', text: 'Triton orbits Neptune backwards, so scientists think it was a wandering dwarf planet that Neptune captured. It has ice volcanoes that spray nitrogen, and it is one of the coldest places we know, minus 235 degrees!' },
        zh: { name: '崔頓', subtitle: '倒著走的衛星', text: '崔頓是倒著繞海王星轉的，所以科學家認為它原本是一顆流浪的矮行星，被海王星抓住了。它有會噴出氮氣的冰火山，也是我們知道最冷的地方之一，零下 235 度！' } }
    ],
    facts: [
      { icon: '🧮', en: { title: 'Found with math', text: 'Neptune was discovered in 1846 using mathematics! Astronomers noticed Uranus wobbling and calculated where a hidden planet must be. When they pointed a telescope there, Neptune was waiting.' }, zh: { title: '用數學找到的', text: '海王星是 1846 年用數學發現的！天文學家發現天王星的軌道怪怪的，就算出一顆隱藏的行星應該在哪裡。望遠鏡一指過去，海王星就在那裡等著。' } },
      { icon: '🎂', en: { title: 'Only one birthday so far', text: 'A year on Neptune lasts 165 Earth years. Since it was discovered in 1846, it has only gone around the Sun once, finishing its first lap in 2011!' }, zh: { title: '到現在只過了一次生日', text: '海王星的一年是 165 個地球年。從 1846 年被發現以來，它只繞了太陽一圈，2011 年才完成第一圈！' } },
      { icon: '🛰️', en: { title: 'One quick visit', text: 'Only Voyager 2 has ever visited Neptune, flying past in 1989. It took 12 years to get there!' }, zh: { title: '短短的一次拜訪', text: '只有航海家 2 號在 1989 年飛過海王星。它花了 12 年才飛到那裡！' } },
      { icon: '💎', en: { title: 'Diamond rain here too', text: 'Just like Uranus, deep inside Neptune the pressure may squeeze carbon into diamonds that sink down like hailstones.' }, zh: { title: '這裡也有鑽石雨', text: '和天王星一樣，海王星深處的壓力可能把碳擠成鑽石，像冰雹一樣往下沉。' } },
      { icon: '🔱', en: { title: 'Named after the sea god', text: 'Because it is so blue, Neptune was named after the Roman god of the sea. His symbol is a three-pointed trident.' }, zh: { title: '以海神命名', text: '因為它這麼藍，海王星用羅馬神話的海神來命名。海神的象徵是一把三叉戟。' } },
      { icon: '🌙', en: { title: 'Sixteen moons', text: 'Neptune has 16 known moons. Triton is by far the biggest; the rest are small, lumpy and hard to see from Earth.' }, zh: { title: '十六顆衛星', text: '海王星已知有 16 顆衛星。崔頓是最大的，其他都很小、凹凸不平，從地球很難看到。' } }
    ]
  }
};

/* Overview (whole solar system) — animated features + fun facts */
var OVERVIEW_CONTENT = {
  name: { en: 'the solar system', zh: '太陽系' },
  features: [
    { key: 'comet', icon: '☄️', chip: { en: '☄️ Comet', zh: '☄️ 彗星' }, label: { en: 'Comet', zh: '彗星' },
      en: { kicker: 'Comet', title: 'The Dirty Snowball', question: 'Why do comets have tails?',
        text: "A comet is a ball of ice and dust, like a dirty snowball, that comes from the cold edge of the solar system. When it gets close to the Sun, the ice turns to gas and the solar wind blows it into a glowing tail millions of kilometers long. Watch closely: the tail always points away from the Sun, even when the comet is flying away from it!" },
      zh: { kicker: '彗星', title: '髒髒的雪球', question: '為什麼彗星有尾巴？',
        text: '彗星是一顆冰和塵埃組成的球，像一顆髒髒的雪球，來自太陽系冰冷的邊緣。當它靠近太陽時，冰會變成氣體，被太陽風吹成一條幾百萬公里長的發光尾巴。仔細看：尾巴永遠背對太陽，就算彗星正在飛離太陽也一樣！' } },
    { key: 'meteors', icon: '🌠', chip: { en: '🌠 Shooting stars', zh: '🌠 流星' }, label: null, illustration: 'meteor',
      en: { kicker: 'Shooting Stars & Meteor Showers', title: 'Not Really Stars', question: 'What is a shooting star?',
        text: "A shooting star is not a star at all! It is a tiny piece of space rock, often smaller than a pea, hitting Earth's air at up to 70 kilometers per second. The air in front of it gets squeezed so hot that the rock glows and burns up in a streak of light, about 80 kilometers above your head. If a piece is big enough to survive and land on the ground, we call it a meteorite. When Earth flies through the dusty trail left behind by a comet, we get a meteor shower: dozens of shooting stars every hour, all seeming to fly out from the same spot in the sky. The Perseids in August and the Geminids in December are the best ones to watch!" },
      zh: { kicker: '流星與流星雨', title: '其實不是星星', question: '流星是什麼？',
        text: '流星根本不是星星！它是一小塊太空石頭，常常比一顆豌豆還小，以每秒高達 70 公里的速度撞進地球的空氣。它前面的空氣被擠壓得超級燙，石頭就發光、燒成一道亮亮的線，這時它大約在你頭頂上 80 公里高的地方。如果有一塊夠大、燒不完掉到地上，我們就叫它「隕石」。當地球飛過彗星留下來的塵埃尾巴時，就會有「流星雨」：每小時幾十顆流星，看起來全都從天空中同一個點飛出來。八月的英仙座流星雨和十二月的雙子座流星雨是最值得看的！' } },
    { key: 'belt', icon: '🪨', chip: { en: '🪨 Asteroid belt', zh: '🪨 小行星帶' }, label: { en: 'Asteroid Belt', zh: '小行星帶' },
      en: { kicker: 'Asteroid Belt', title: 'Leftover Building Blocks', question: 'What is between Mars and Jupiter?',
        text: "Millions of rocky asteroids orbit in a wide belt between Mars and Jupiter. They are leftover pieces from when the planets were built, and Jupiter's strong gravity stopped them from sticking together into a planet. The biggest one, Ceres, is a round dwarf planet 940 kilometers wide. Even so, the belt is mostly empty space: spacecraft fly right through it without hitting anything!" },
      zh: { kicker: '小行星帶', title: '蓋行星剩下的積木', question: '火星和木星之間有什麼？',
        text: '火星和木星之間有一條寬寬的帶子，裡面有幾百萬顆石頭做的小行星。它們是當年蓋行星時剩下的碎片，木星強大的引力讓它們沒辦法黏在一起變成行星。最大的一顆叫穀神星，是一顆圓圓的矮行星，有 940 公里寬。不過小行星帶大部分都是空的，太空船直接穿過去都不會撞到東西！' } },
    { key: 'kuiper', icon: '🧊', chip: { en: '🧊 Kuiper belt & Pluto', zh: '🧊 古柏帶與冥王星' }, label: { en: 'Kuiper Belt', zh: '古柏帶' },
      en: { kicker: 'Kuiper Belt', title: 'Where Pluto Lives', question: 'Where did Pluto go?',
        text: 'Beyond Neptune there is a huge ring of icy worlds called the Kuiper Belt, and Pluto lives there! In 2006 scientists decided Pluto is a dwarf planet, because it shares its neighborhood with lots of other icy objects. It is still out there, still round, with a giant heart-shaped glacier on its surface, and it takes 248 years to go around the Sun once.' },
      zh: { kicker: '古柏帶', title: '冥王星住的地方', question: '冥王星去哪了？',
        text: '海王星外面有一圈巨大的冰冷小世界，叫做「古柏帶」，冥王星就住在那裡！2006 年科學家決定冥王星是「矮行星」，因為它的鄰居還有很多其他的冰冷天體。它還在那裡、還是圓的，表面有一個超大的愛心形冰川，繞太陽一圈要 248 年。' } },
    { key: 'voyager', icon: '🛰️', chip: { en: '🛰️ Voyager 1', zh: '🛰️ 航海家一號' }, label: { en: 'Voyager 1', zh: '航海家一號' },
      en: { kicker: 'Voyager 1', title: 'The Farthest Traveler', question: 'What is that tiny spacecraft?',
        text: 'Voyager 1 left Earth in 1977 and is now the farthest human-made object ever, more than 24 billion kilometers away, beyond all the planets. It carries a golden record with music and hello in 55 languages, in case anyone out there ever finds it. Its radio messages take almost a whole day to reach us.' },
      zh: { kicker: '航海家一號', title: '走得最遠的旅行者', question: '那個小小的太空船是什麼？',
        text: '航海家一號在 1977 年離開地球，現在是人類做過走得最遠的東西，距離超過 240 億公里，已經飛出所有行星之外。它帶著一張金唱片，裡面有音樂和 55 種語言的「你好」，萬一外面有誰撿到它。它發回來的無線電訊號要飛將近一整天才到得了地球。' } }
  ],
  facts: [
    { key: 'sunlight', icon: '💡',
      en: { title: 'Eight minutes to Earth', text: 'Light is the fastest thing in the universe, about 300,000 kilometers every second. Even so, sunlight takes 8 minutes and 20 seconds to reach Earth, over 4 hours to reach Neptune, and more than a year to leave the solar system. Watch the little spark race from the Sun to Earth!' },
      zh: { title: '八分鐘到地球', text: '光是宇宙裡最快的東西，每秒鐘大約跑 30 萬公里。就算這麼快，陽光還是要 8 分 20 秒才到地球，超過 4 小時才到海王星，超過一年才能飛出太陽系。看看那顆小火花從太陽衝到地球！' } },
    { icon: '🎂', en: { title: 'Born from a cloud', text: 'About 4.6 billion years ago, a giant spinning cloud of gas and dust collapsed. The Sun formed in the middle, and the planets grew from the leftover disc. That is why they all orbit in the same direction, like they are on a giant flat pancake.' }, zh: { title: '從一朵雲誕生', text: '大約 46 億年前，一朵巨大的、旋轉的氣體和塵埃雲塌了下來。太陽在中間形成，行星從剩下的圓盤裡長出來。所以它們才會全部往同一個方向繞，像放在一片巨大的扁扁煎餅上。' } },
    { icon: '🧠', en: { title: 'A trick to remember the order', text: 'My Very Excellent Mother Just Served Us Noodles: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune!' }, zh: { title: '記住順序的口訣', text: '「水金地火木土天海」：水星、金星、地球、火星、木星、土星、天王星、海王星！' } },
    { icon: '⚖️', en: { title: 'The Sun is almost everything', text: 'The Sun holds 99.8 percent of everything in the solar system. All eight planets together are just a sprinkle, and they could all fit side by side in the space between Earth and the Moon!' }, zh: { title: '太陽幾乎就是全部', text: '太陽系 99.8% 的東西都在太陽裡。八顆行星加起來只是一點點，而且把它們排成一排，可以塞進地球和月球之間的空隙裡！' } },
    { icon: '🏀', en: { title: 'How tiny we are', text: 'If the Sun were a basketball, Earth would be a peppercorn about 26 meters away, and Neptune would be a small marble almost 800 meters away.' }, zh: { title: '我們有多小', text: '如果太陽是一顆籃球，地球就是 26 公尺外的一粒胡椒，海王星則是快 800 公尺外的一顆小彈珠。' } },
    { icon: '🚗', en: { title: 'A very long drive', text: 'If you could drive a car to the Sun at 100 kilometers per hour without stopping, it would take 170 years. Driving to Neptune would take about 5,000 years!' }, zh: { title: '超級長的車程', text: '如果你能開車以時速 100 公里不停地開到太陽，要開 170 年。開到海王星大約要 5000 年！' } },
    { icon: '🌌', en: { title: 'We are moving too', text: 'The whole solar system is zooming around the center of our galaxy, the Milky Way, at 828,000 kilometers per hour. One lap takes 230 million years. The last time we were here, dinosaurs were walking on Earth!' }, zh: { title: '我們也在移動', text: '整個太陽系正以每小時 82 萬 8 千公里的速度繞著銀河系的中心跑。繞一圈要 2 億 3 千萬年。上一次經過這個位置時，恐龍還在地球上走來走去！' } },
    { icon: '🪐', en: { title: 'Three kinds of planets', text: 'Mercury, Venus, Earth and Mars are small rocky planets. Jupiter and Saturn are gas giants. Uranus and Neptune are ice giants. The farther from the Sun, the colder and stranger things get.' }, zh: { title: '三種行星', text: '水星、金星、地球和火星是小小的岩石行星。木星和土星是氣體巨行星。天王星和海王星是冰巨行星。離太陽越遠，就越冷、越奇怪。' } },
    { icon: '🔄', en: { title: 'Two odd spinners', text: 'Seen from above, every planet orbits the Sun counterclockwise. Most spin that way too, except Venus, which spins backwards, and Uranus, which rolls on its side!' }, zh: { title: '兩個怪怪的自轉', text: '從上面看，每顆行星都是逆時針繞太陽。大部分也是逆時針自轉，只有金星是倒著轉，天王星則是躺著滾！' } }
  ]
};

/* Beyond the solar system — a black hole scene (reached from the overview chip bar) */
var BEYOND_CONTENT = {
  name: { en: 'Beyond the Solar System', zh: '太陽系之外' },
  subtitle: { en: 'A Black Hole', zh: '黑洞' },
  crumb: { en: '⚫ Black hole', zh: '⚫ 黑洞' },
  sunLabel: { en: 'Our Sun · 26,000 light-years away', zh: '我們的太陽 · 在 2.6 萬光年外' },
  hotspots: [
    { pos: [0.4, 1.4, 2.6], color: '#c9d6ff', icon: '⚫',
      en: { kicker: 'Event Horizon', title: 'What Is a Black Hole?', question: 'What is a black hole?',
        text: 'A black hole is a place where so much stuff is squeezed into such a tiny space that its gravity becomes unbeatable. Not even light, the fastest thing there is, can escape once it crosses the edge, called the event horizon. That is why the middle looks perfectly black.' },
      zh: { kicker: '事件視界', title: '黑洞是什麼？', question: '黑洞是什麼？',
        text: '黑洞是一個把超級多的東西擠進超級小的空間裡的地方，它的重力強到沒有東西打得贏。連宇宙裡最快的光，一旦越過它的邊緣（叫做「事件視界」），也逃不出來。所以它的中間看起來是全黑的。' } },
    { pos: [6.2, 0.3, 1.8], color: '#ffb347', icon: '🌀',
      en: { kicker: 'Accretion Disc', title: 'Why Does It Glow?', question: 'Why is there a glowing ring around it?',
        text: 'The black hole itself is dark, but gas and dust spiraling toward it rub together and heat up to millions of degrees, glowing bright orange and white. This swirling disc is the part we can actually see. The glow that seems to bend over the top and bottom is real light being curved by gravity!' },
      zh: { kicker: '吸積盤', title: '為什麼它會發光？', question: '為什麼周圍有一圈發光的東西？',
        text: '黑洞本身是黑的，但被它吸過去的氣體和塵埃一邊旋轉一邊互相摩擦，熱到好幾百萬度，發出亮亮的橘色和白色光。這個旋轉的圓盤就是我們真正看得到的部分。看起來像彎過黑洞上下的光，是真的被重力彎曲的光！' } },
    { pos: [-5.2, 2.8, 0.6], color: '#7dffd8', icon: '🧲',
      en: { kicker: 'Gravity', title: 'Would We Get Sucked In?', question: 'Would we get sucked in?',
        text: "No! A black hole is not a vacuum cleaner. From far away, its gravity works just like any star's. If the Sun were swapped for a black hole of exactly the same weight, Earth would keep orbiting just like it does now. It would only get very dark and very cold." },
      zh: { kicker: '重力', title: '我們會被吸進去嗎？', question: '我們會被吸進去嗎？',
        text: '不會！黑洞不是吸塵器。離得夠遠的時候，它的重力就跟普通的星星一樣。如果把太陽換成一顆一樣重的黑洞，地球還是會像現在一樣繞著它轉，只是會變得非常暗、非常冷。' } },
    { pos: [16, 5, -8], color: '#fff1a8', icon: '☀️',
      en: { kicker: 'Our Sun', title: 'Will the Sun Become One?', question: 'Will our Sun become a black hole?',
        text: 'No, the Sun is much too small. Only stars at least twenty times heavier than the Sun end their lives as black holes. In about five billion years the Sun will puff up into a red giant, and then shrink into a quiet, tiny white dwarf. That little dot over there is the Sun, seen from 26,000 light-years away.' },
      zh: { kicker: '我們的太陽', title: '太陽會變成黑洞嗎？', question: '我們的太陽會變成黑洞嗎？',
        text: '不會，太陽太小了。只有比太陽重至少二十倍的星星，一生結束時才會變成黑洞。大約五十億年後，太陽會膨脹成一顆紅巨星，然後縮成一顆安靜的小白矮星。那邊那個小點就是太陽，從 2.6 萬光年外看過去的樣子。' } },
    { pos: [0, -4.6, 1.2], color: '#c9b8ff', icon: '🌌',
      en: { kicker: 'Sagittarius A*', title: 'The Giant in Our Galaxy', question: 'Is there a black hole near us?',
        text: 'Right in the middle of our galaxy, the Milky Way, sits a giant black hole called Sagittarius A star. It weighs as much as four million Suns! Our whole solar system, and you, are slowly circling around it, 26,000 light-years away, perfectly safe.' },
      zh: { kicker: '人馬座 A*', title: '我們銀河系裡的巨人', question: '我們附近有黑洞嗎？',
        text: '在我們銀河系的正中央，住著一個叫「人馬座 A 星」的巨大黑洞。它有四百萬顆太陽那麼重！整個太陽系，還有你，都在 2.6 萬光年外慢慢地繞著它轉，非常安全。' } },
    { pos: [-2.6, -2.4, 2.4], color: '#ff9d42', icon: '📸',
      en: { kicker: 'First Photo', title: 'The Orange Doughnut', question: 'Has anyone ever seen one?',
        text: 'Yes! In 2019 scientists linked telescopes all over the world so they worked together like one telescope as big as Earth, and took the first-ever picture of a black hole. It looked like a fuzzy orange doughnut: the dark shadow of the hole, with glowing gas all around it.' },
      zh: { kicker: '第一張照片', title: '橘色甜甜圈', question: '有人真的看過黑洞嗎？',
        text: '有！2019 年科學家把全世界的望遠鏡連在一起，讓它們像一台和地球一樣大的望遠鏡一起工作，拍下了史上第一張黑洞照片。它看起來像一個模糊的橘色甜甜圈：中間是黑洞的影子，周圍是發光的氣體。' } }
  ],
  moons: [],
  facts: [
    { icon: '🍝', en: { title: 'Stretched like spaghetti', text: 'If you fell toward a black hole feet first, gravity would pull your feet much harder than your head, stretching you long and thin. Scientists really do call this spaghettification!' }, zh: { title: '拉成義大利麵', text: '如果你腳先掉向黑洞，重力拉你的腳會比拉你的頭用力很多，把你拉得又長又細。科學家真的把這叫做「義大利麵化」！' } },
    { icon: '⏱️', en: { title: 'Time slows down', text: 'Near a black hole, time really does run slower. If you could hover close to one for a while and come back, your friends at home would have grown older than you.' }, zh: { title: '時間會變慢', text: '在黑洞附近，時間真的會走得比較慢。如果你能在黑洞旁邊待一陣子再回來，家裡的朋友會變得比你老。' } },
    { icon: '🐣', en: { title: 'Born from a dying star', text: 'Most black holes are born when a giant star runs out of fuel and collapses in on itself in a huge explosion called a supernova.' }, zh: { title: '從垂死的星星誕生', text: '大部分的黑洞是在一顆巨大的星星燃料用完、往自己內部塌下去、然後發生一場叫「超新星」的大爆炸時誕生的。' } },
    { icon: '📏', en: { title: 'Tiny but heavy', text: 'To turn Earth into a black hole, you would have to squeeze the whole planet down to the size of a marble. Its gravity would stay the same, but nothing could escape from its tiny surface.' }, zh: { title: '很小卻很重', text: '要把地球變成黑洞，得把整顆地球擠到一顆彈珠那麼小。它的重力不會變，但沒有東西能從它小小的表面逃出來。' } },
    { icon: '🧠', en: { title: 'Einstein predicted them', text: 'Albert Einstein\'s equations predicted black holes in 1915, long before anyone could see one. The name "black hole" was only invented in 1967.' }, zh: { title: '愛因斯坦早就算出來了', text: '愛因斯坦的方程式在 1915 年就預測了黑洞，那時候還沒有人看過。「黑洞」這個名字到 1967 年才被發明出來。' } },
    { icon: '🎧', en: { title: 'A black hole can sing', text: 'NASA recorded ripples of pressure coming from a black hole in a faraway galaxy and turned them into sound. Its note is 57 octaves below middle C, far too deep for our ears, so they raised it up so we could hear it.' }, zh: { title: '黑洞會唱歌', text: 'NASA 記錄了一個遙遠星系裡黑洞發出的壓力波，把它變成聲音。它的音高比中央 C 低 57 個八度，低到耳朵聽不見，所以科學家把它調高讓我們能聽到。' } }
  ]
};

/* Dwarf planets (overview) — item 0 is the intro card; the rest are real objects on the map */
OVERVIEW_CONTENT.dwarfs = [
  { key: 'intro', icon: '🪐',
    en: { name: 'Dwarf Planets', subtitle: 'What makes a dwarf planet?',
      text: 'A dwarf planet is round like a planet and goes around the Sun like a planet, but it is not big enough to sweep its neighborhood clear of other space rocks. There are five official ones: Ceres, Pluto, Haumea, Makemake and Eris. Tap Next to meet them one by one, or find them glowing on the map!' },
    zh: { name: '矮行星', subtitle: '什麼是矮行星？',
      text: '矮行星和行星一樣是圓的、一樣繞著太陽轉，但它不夠大，沒辦法把自己軌道附近的其他太空岩石清乾淨。官方認定的有五顆：穀神星、冥王星、妊神星、鳥神星和鬩神星。按「下一個」一顆一顆認識它們，或是在地圖上找找看發光的它們！' } },
  { key: 'ceres', icon: '🪨', label: { en: 'Ceres', zh: '穀神星' },
    en: { name: 'Ceres', subtitle: 'The only dwarf planet in the asteroid belt',
      text: "Ceres is the biggest thing in the asteroid belt, about 940 kilometers across, and the closest dwarf planet to Earth. It has water ice under its surface, and bright white salty spots inside one crater that puzzled scientists for years. NASA's Dawn spacecraft orbited it in 2015." },
    zh: { name: '穀神星', subtitle: '小行星帶裡唯一的矮行星',
      text: '穀神星是小行星帶裡最大的東西，大約 940 公里寬，也是離地球最近的矮行星。它的地表底下有水冰，有一個隕石坑裡還有亮白色的鹽斑，讓科學家困惑了好幾年。NASA 的曙光號太空船在 2015 年繞著它飛。' } },
  { key: 'pluto', icon: '❤️', label: { en: 'Pluto', zh: '冥王星' },
    en: { name: 'Pluto', subtitle: 'The famous one',
      text: 'Pluto was called the ninth planet for 76 years. It is smaller than our Moon, has five moons of its own, a heart-shaped glacier of frozen nitrogen, and mountains made of water ice. Its year lasts 248 Earth years. New Horizons flew past it in 2015 and sent back the first close-up pictures.' },
    zh: { name: '冥王星', subtitle: '最有名的那顆',
      text: '冥王星當了 76 年的「第九顆行星」。它比我們的月球還小，自己有五顆衛星，有一片愛心形的凍氮冰川，還有水冰做的山。它的一年是 248 個地球年。新視野號在 2015 年飛過它，傳回第一批近距離照片。' } },
  { key: 'haumea', icon: '🥚', label: { en: 'Haumea', zh: '妊神星' },
    en: { name: 'Haumea', subtitle: 'The spinning egg',
      text: 'Haumea spins faster than anything else its size in the solar system: one day lasts only four hours! It spins so fast that it has been stretched into the shape of an egg. It even has a thin ring and two small moons. It is named after the Hawaiian goddess of birth.' },
    zh: { name: '妊神星', subtitle: '旋轉的蛋',
      text: '妊神星是太陽系裡同樣大小的東西中轉得最快的：它的一天只有四小時！轉得太快，整顆被甩成了蛋的形狀。它還有一圈細細的環和兩顆小衛星。名字來自夏威夷的生育女神。' } },
  { key: 'makemake', icon: '🟤', label: { en: 'Makemake', zh: '鳥神星' },
    en: { name: 'Makemake', subtitle: 'The reddish one',
      text: 'Makemake is a bit smaller than Pluto and covered in frozen methane, which gives it a reddish-brown color. It was discovered just after Easter in 2005, so it was named after the creator god of the Easter Island people. It has one tiny moon.' },
    zh: { name: '鳥神星', subtitle: '紅棕色的那顆',
      text: '鳥神星比冥王星小一點，表面蓋著凍結的甲烷，所以是紅棕色的。它是在 2005 年復活節剛過後被發現的，因此用復活節島原住民的創世神來命名。它有一顆小小的衛星。' } },
  { key: 'eris', icon: '⚖️', label: { en: 'Eris', zh: '鬩神星' },
    en: { name: 'Eris', subtitle: 'The troublemaker',
      text: "Eris is the one that changed everything. When it was found in 2005 it turned out to be heavier than Pluto, so scientists had to decide: is Eris the tenth planet, or is Pluto not a planet? They invented the words 'dwarf planet' for both. Eris is three times farther from the Sun than Pluto, and it is named after the Greek goddess of arguments!" },
    zh: { name: '鬩神星', subtitle: '惹麻煩的那顆',
      text: '鬩神星就是改變一切的那顆。2005 年它被發現時，竟然比冥王星還重，科學家只好做決定：鬩神星是第十顆行星，還是冥王星其實不是行星？最後他們發明了「矮行星」這個詞給兩顆一起用。鬩神星離太陽比冥王星遠三倍，名字來自希臘神話裡的紛爭女神！' } }
];
OVERVIEW_CONTENT.dwarfChip = { en: '🪐 Dwarf planets', zh: '🪐 矮行星' };
OVERVIEW_CONTENT.dwarfKicker = { en: 'Dwarf planet', zh: '矮行星' };

/* The Milky Way */
var GALAXY_CONTENT = {
  name: { en: 'The Milky Way', zh: '銀河系' },
  subtitle: { en: 'Our Home Galaxy', zh: '我們的家鄉星系' },
  crumb: { en: '🌌 Milky Way', zh: '🌌 銀河系' },
  youAreHere: { en: 'You are here ☀️', zh: '你在這裡 ☀️' },
  hotspots: [
    { key: 'center', pos: [0, 2.2, 0], color: '#ffe3a8', icon: '⚫', link: 'beyond', linkLabel: { en: '⚫ Go to the black hole →', zh: '⚫ 前往黑洞 →' },
      en: { kicker: 'Galactic Center', title: 'What Is in the Middle?', question: 'What is at the center of the galaxy?',
        text: 'The center is packed with old yellow stars, and hiding among them is a giant black hole called Sagittarius A star, as heavy as four million Suns. Everything in the galaxy, including our Sun, slowly circles around it.' },
      zh: { kicker: '銀河系中心', title: '中間有什麼？', question: '銀河系的中心有什麼？',
        text: '中心擠滿了年老的黃色星星，而躲在它們之間的，是一個叫「人馬座 A 星」的巨大黑洞，有四百萬顆太陽那麼重。銀河系裡的所有東西，包括我們的太陽，都慢慢地繞著它轉。' } },
    { key: 'sun', pos: 'sun', color: '#fff1a8', icon: '☀️',
      en: { kicker: 'You Are Here', title: 'Our Tiny Spot', question: 'Where is the Sun in the galaxy?',
        text: 'Our Sun is just one of about 200 billion stars in the Milky Way. It sits about 26,000 light-years from the center, on a small arm called the Orion Arm, partway out toward the edge. From here, one trip around the galaxy takes about 230 million years.' },
      zh: { kicker: '你在這裡', title: '我們小小的位置', question: '太陽在銀河系的哪裡？',
        text: '我們的太陽只是銀河系大約兩千億顆星星裡的一顆。它離中心大約 2.6 萬光年，位在一條叫「獵戶臂」的小旋臂上，離邊緣還有一段距離。從這裡繞銀河系一圈，大約要 2 億 3 千萬年。' } },
    { key: 'arm', pos: 'arm', color: '#9ad1ff', icon: '🌀',
      en: { kicker: 'Spiral Arms', title: 'Why the Swirl?', question: 'Why does it have spiral arms?',
        text: 'The arms are not solid. They are like traffic jams of stars and gas: stars slow down and bunch up as they pass through, and the squeezed gas gives birth to bright new blue stars, which is why the arms glow so brightly. The Milky Way has two big arms and a few smaller ones, plus a bar of stars across the middle.' },
      zh: { kicker: '旋臂', title: '為什麼是漩渦狀？', question: '為什麼它有旋臂？',
        text: '旋臂不是實心的。它們像是星星和氣體的塞車路段：星星經過時會變慢、擠在一起，被擠壓的氣體就生出明亮的藍色新星星，所以旋臂才會這麼亮。銀河系有兩條大旋臂和幾條小的，中間還有一根由星星組成的棒子。' } },
    { key: 'band', pos: [34, -3, 18], color: '#e8f0ff', icon: '🌉',
      en: { kicker: 'Night Sky', title: 'The Milky Band', question: 'Why is it called the Milky Way?',
        text: 'On a very dark night you can see a faint, milky band of light stretching across the sky. That is our own galaxy seen from the inside, edge on, like looking across a plate from its rim. Ancient people thought it looked like spilled milk, which is where the name comes from.' },
      zh: { kicker: '夜空', title: '那條乳白色的帶子', question: '為什麼叫「銀河」？',
        text: '在很暗的夜晚，你可以看到一條淡淡的、乳白色的光帶橫跨天空。那就是從裡面看我們自己的星系，從側面看過去，像從盤子的邊緣看整個盤子。古時候的人覺得它像灑出來的牛奶，英文名字「牛奶路」就是這樣來的；中文則覺得它像天上的一條河。' } },
    { key: 'orion', pos: 'orion', color: '#ff9ad1', icon: '🌸',
      en: { kicker: 'Nebula', title: 'A Star Nursery', question: 'What is a nebula?',
        text: 'A nebula is a giant cloud of gas and dust floating between the stars. Some nebulas are star nurseries: gravity slowly pulls the gas into clumps, the clumps get hotter and hotter, and finally they light up as brand-new stars. The Orion Nebula, only 1,300 light-years from us, is making hundreds of new stars right now. You can see it with your own eyes as a fuzzy patch in the sword of Orion. Nebulas are drawn much bigger here than they really are.' },
      zh: { kicker: '星雲', title: '星星的育嬰房', question: '星雲是什麼？',
        text: '星雲是飄在星星之間的巨大氣體和塵埃雲。有些星雲是星星的育嬰房：重力慢慢把氣體拉成一團一團，這些團越來越熱，最後亮起來變成全新的星星。獵戶座星雲離我們只有 1300 光年，現在正在製造幾百顆新星星。你用肉眼就能在獵戶座的「腰帶」下方看到它，像一小團霧。這裡畫的星雲比真實的大很多。' } },
    { key: 'ring', pos: 'ring', color: '#7dffd8', icon: '💍',
      en: { kicker: 'Planetary Nebula', title: "A Star's Beautiful Goodbye", question: 'What happens when a star like the Sun dies?',
        text: 'When a star like our Sun runs out of fuel, it gently puffs its outer layers into space, making a glowing shell of gas called a planetary nebula, like the Ring Nebula. The tiny hot core left behind is a white dwarf. Despite the name, it has nothing to do with planets: early astronomers just thought these round glowing shells looked like planets in their small telescopes.' },
      zh: { kicker: '行星狀星雲', title: '星星美麗的告別', question: '像太陽這樣的星星死掉會怎樣？',
        text: '當像太陽這樣的星星燃料用完時，它會輕輕地把外層吹到太空中，形成一個發光的氣體殼，叫做「行星狀星雲」，像環狀星雲那樣。留在中間的小小熱核心，就是白矮星。雖然名字有「行星」，它跟行星一點關係都沒有：只是早期的天文學家用小望遠鏡看，覺得這些圓圓的發光殼長得像行星。' } },
    { key: 'crab', pos: 'crab', color: '#ffb347', icon: '💥',
      en: { kicker: 'Supernova Remnant', title: 'What a Giant Star Leaves Behind', question: 'What about really big stars?',
        text: 'Big, heavy stars end with a bang: a supernova explosion that can outshine a whole galaxy for weeks. The Crab Nebula is the leftover of a supernova that people saw in the year 1054, so bright it was visible in daytime! In the middle spins a neutron star, a city-sized ball so heavy that a teaspoon of it would weigh a billion tons. The very heaviest stars collapse into black holes instead.' },
      zh: { kicker: '超新星殘骸', title: '巨星留下的痕跡', question: '那很大的星星呢？',
        text: '又大又重的星星會用大爆炸結束一生：超新星爆炸可以在好幾個星期裡比整個星系還亮。蟹狀星雲就是西元 1054 年人們看到的一次超新星留下來的，當時亮到白天都看得見！它的中間轉著一顆中子星，一顆城市大小的球，重到一茶匙就有十億公噸。而最重的那些星星，則會塌縮成黑洞。' } },
    { key: 'starlife', pos: 'starlife', color: '#fff1a8', icon: '⭐', illustration: 'starlife', chip: { en: '⭐ Life of a star', zh: '⭐ 星星的一生' },
      en: { kicker: 'Life of a Star', title: 'From Cloud to Star to… What?', question: 'How is a star born, and how does it end?',
        text: 'Every star begins inside a nebula, a cold cloud of gas and dust. Gravity slowly squeezes the cloud together until the middle gets so hot that it starts to shine: a star is born. It then glows steadily for millions or billions of years, like our Sun. How it ends depends on how heavy it is. A star like the Sun swells into a red giant, gently puffs off its outer layers as a planetary nebula, and leaves a tiny white dwarf. A star more than twenty times heavier swells into a red supergiant and then explodes as a supernova, leaving behind a neutron star, or, if it was truly enormous, a black hole. The gas it throws out becomes the nebula for the next generation of stars.' },
      zh: { kicker: '星星的一生', title: '從雲到星星，然後呢？', question: '星星是怎麼誕生、怎麼結束的？',
        text: '每一顆星星都是在星雲裡誕生的，那是一團冰冷的氣體和塵埃。重力慢慢把雲擠在一起，直到中間熱到開始發光：一顆星星就誕生了。接著它會像我們的太陽一樣，安穩地發光幾百萬到幾十億年。它怎麼結束，要看它有多重。像太陽這樣的星星會膨脹成紅巨星，輕輕地把外層吹成行星狀星雲，留下一顆小小的白矮星。比太陽重二十倍以上的星星，會膨脹成紅超巨星，然後以超新星大爆炸結束，留下一顆中子星；如果它真的超級巨大，就會變成黑洞。它噴出去的氣體，會變成下一代星星的星雲。' } },
    { key: 'size', pos: [-38, 4, 6], color: '#c9b8ff', icon: '📏',
      en: { kicker: 'Size', title: 'Bigger Than You Can Imagine', question: 'How big is the Milky Way?',
        text: 'Light, the fastest thing there is, takes about 100,000 years to cross the Milky Way from one side to the other. If the whole galaxy were the size of a football field, our entire solar system would be smaller than a grain of sand.' },
      zh: { kicker: '大小', title: '大到無法想像', question: '銀河系有多大？',
        text: '光是最快的東西，卻要花大約十萬年才能從銀河系的一邊跑到另一邊。如果整個銀河系縮成一座足球場，我們整個太陽系會比一粒沙子還小。' } }
  ],
  moons: [],
  facts: [
    { icon: '🥛', en: { title: 'A name about milk', text: 'The word "galaxy" comes from the Greek word for milk, because of the milky band in the night sky. So the Milky Way\'s name really means "the milky milky way"!' }, zh: { title: '一個關於牛奶的名字', text: '英文的「星系」（galaxy）來自希臘文的「牛奶」，因為夜空中那條帶子看起來像牛奶。所以銀河系的英文名字其實是「牛奶牛奶路」！' } },
    { icon: '🚫', en: { title: 'No photo from outside', text: 'Every picture of the whole Milky Way is a drawing or a photo of a different galaxy. No spacecraft could ever fly far enough out to take the real photo: it would take millions of years.' }, zh: { title: '沒有從外面拍的照片', text: '所有「整個銀河系」的圖片都是畫的，或是別的星系的照片。沒有太空船能飛得夠遠去拍真正的照片，因為那要花幾百萬年。' } },
    { icon: '🎂', en: { title: 'Almost as old as the universe', text: 'The Milky Way is about 13.6 billion years old, nearly as old as the universe itself. Our Sun is a latecomer, only 4.6 billion years old.' }, zh: { title: '幾乎和宇宙一樣老', text: '銀河系大約 136 億歲，幾乎和宇宙本身一樣老。我們的太陽是後來才加入的，只有 46 億歲。' } },
    { icon: '👻', en: { title: 'Mostly invisible', text: 'The stars we can see are only a small part of the galaxy. Most of its weight is a mysterious invisible stuff called dark matter, wrapped around it like a giant cloud.' }, zh: { title: '大部分是看不見的', text: '我們看得到的星星只是銀河系的一小部分。它大部分的重量來自一種神祕、看不見的東西，叫「暗物質」，像一團巨大的雲包著整個星系。' } },
    { icon: '💫', en: { title: 'New stars every year', text: 'The Milky Way makes about seven new stars every year from clouds of gas. Some day, planets may form around them too.' }, zh: { title: '每年都有新星星', text: '銀河系每年會從氣體雲裡製造出大約七顆新星星。有一天，它們旁邊也可能會長出行星。' } },
    { icon: '♻️', en: { title: 'You are made of star stuff', text: 'Gas from old nebulas becomes new stars and planets. The iron in your blood and the calcium in your bones were cooked inside stars that exploded long before the Sun was born. Every one of us is made of recycled star dust!' }, zh: { title: '你是星星做的', text: '老星雲的氣體會變成新的星星和行星。你血液裡的鐵、骨頭裡的鈣，都是在太陽誕生之前很久就爆炸的星星裡煮出來的。我們每個人都是回收再利用的星塵做的！' } },
    { icon: '🤝', en: { title: 'A group of friends', text: 'The Milky Way is not alone. It belongs to the Local Group, a little family of about 80 galaxies. Its two biggest friends are Andromeda and the Triangulum galaxy.' }, zh: { title: '一群好朋友', text: '銀河系不是孤單的。它屬於「本星系群」，一個大約 80 個星系的小家族。它最大的兩個朋友是仙女座星系和三角座星系。' } }
  ]
};

/* Other galaxies */
var GALAXIES_CONTENT = {
  name: { en: 'Other Galaxies', zh: '其他星系' },
  subtitle: { en: 'A Universe of Galaxies', zh: '星系的宇宙' },
  crumb: { en: '🌠 Other galaxies', zh: '🌠 其他星系' },
  labels: { milky: { en: 'Milky Way', zh: '銀河系' }, andromeda: { en: 'Andromeda', zh: '仙女座星系' }, elliptical: { en: 'Elliptical galaxy', zh: '橢圓星系' }, irregular: { en: 'Irregular galaxy', zh: '不規則星系' }, lmc: { en: 'Large Magellanic Cloud', zh: '大麥哲倫雲' }, smc: { en: 'Small Magellanic Cloud', zh: '小麥哲倫雲' } },
  hotspots: [
    { key: 'andromeda', pos: 'andromeda', color: '#c9d6ff', icon: '🌀',
      en: { kicker: 'Andromeda', title: 'Our Giant Neighbor', question: 'What is the closest big galaxy?',
        text: 'Andromeda is the closest big galaxy to us, about 2.5 million light-years away, and it is even bigger than the Milky Way, with maybe a trillion stars. On a dark autumn night you can see it with your own eyes as a faint smudge. It is the farthest thing a human eye can see.' },
      zh: { kicker: '仙女座星系', title: '我們巨大的鄰居', question: '離我們最近的大星系是哪個？',
        text: '仙女座星系是離我們最近的大星系，大約 250 萬光年遠，而且比銀河系還大，可能有一兆顆星星。在秋天很暗的夜晚，你可以用肉眼看到它，像一小團淡淡的霧。它是人類眼睛能看到最遠的東西。' } },
    { key: 'collision', pos: 'between', color: '#ff9d42', icon: '💥',
      en: { kicker: 'Collision', title: 'A Galaxy Crash', question: 'Will they crash into each other?',
        text: 'Yes! Andromeda and the Milky Way are flying toward each other at 400,000 kilometers per hour. In about 4.5 billion years they will merge into one giant galaxy, nicknamed Milkomeda. But do not worry: stars are so far apart that almost none of them will actually bump into each other.' },
      zh: { kicker: '碰撞', title: '星系大相撞', question: '它們會撞在一起嗎？',
        text: '會！仙女座星系和銀河系正以每小時 40 萬公里的速度朝對方飛去。大約 45 億年後，它們會合併成一個超大的星系，暱稱叫「銀河仙女座」。不過別擔心：星星之間的距離太遠了，幾乎沒有任何星星會真的撞到。' } },
    { key: 'spiral', pos: 'milky', color: '#9ad1ff', icon: '🌀',
      en: { kicker: 'Galaxy Shapes', title: 'Spiral Galaxies', question: 'What shapes do galaxies come in?',
        text: 'Galaxies come in three main shapes. Spiral galaxies, like ours and Andromeda, are flat discs with swirling arms full of gas and young blue stars. They are still busy making new stars.' },
      zh: { kicker: '星系的形狀', title: '螺旋星系', question: '星系有哪些形狀？',
        text: '星系主要有三種形狀。螺旋星系，像我們的銀河系和仙女座星系，是扁扁的圓盤，有充滿氣體和年輕藍色星星的旋臂。它們還在忙著製造新星星。' } },
    { key: 'elliptical', pos: 'elliptical', color: '#ffe3a8', icon: '🟡',
      en: { kicker: 'Galaxy Shapes', title: 'Elliptical Galaxies', question: 'What is the yellow blob?',
        text: 'Elliptical galaxies are smooth, egg-shaped balls of old yellow and red stars. They have almost no gas left, so they hardly make any new stars. The biggest galaxies in the whole universe are giant ellipticals.' },
      zh: { kicker: '星系的形狀', title: '橢圓星系', question: '那團黃色的是什麼？',
        text: '橢圓星系是光滑、蛋形的一團年老的黃色和紅色星星。它們幾乎沒有剩下的氣體，所以幾乎不再製造新星星。宇宙中最大的星系都是巨大的橢圓星系。' } },
    { key: 'irregular', pos: 'irregular', color: '#7dffd8', icon: '☁️',
      en: { kicker: 'Galaxy Shapes', title: 'Irregular Galaxies', question: 'What about the messy one?',
        text: 'Irregular galaxies have no neat shape at all. They are often small, and got pulled out of shape by a bigger neighbor. The Milky Way has two of them close by, the Magellanic Clouds, which you can see from the southern half of Earth.' },
      zh: { kicker: '星系的形狀', title: '不規則星系', question: '那個亂亂的是什麼？',
        text: '不規則星系沒有整齊的形狀。它們通常很小，是被旁邊更大的星系拉扯變形的。銀河系附近就有兩個，叫「麥哲倫雲」，從地球的南半球可以看到。' } },
    { key: 'magellanic', pos: 'magellanic', color: '#bfe3ff', icon: '☁️',
      en: { kicker: 'Magellanic Clouds', title: 'Our Little Neighbors', question: 'What are those two small clouds?',
        text: 'The Large and Small Magellanic Clouds are two dwarf galaxies that circle around the Milky Way, about 160,000 and 200,000 light-years away. Each has a few billion stars. From the southern half of Earth they look like two glowing clouds torn off the Milky Way. They are named after the explorer Magellan, whose crew wrote about them while sailing around the world in 1519.' },
      zh: { kicker: '麥哲倫雲', title: '我們的小鄰居', question: '那兩團小小的雲是什麼？',
        text: '大麥哲倫雲和小麥哲倫雲是兩個繞著銀河系轉的矮星系，距離大約 16 萬和 20 萬光年。每一個都有幾十億顆星星。從地球的南半球看，它們像兩團從銀河上撕下來的發光雲朵。名字來自探險家麥哲倫，1519 年他的船隊環球航行時把它們記錄了下來。' } },
    { key: 'count', pos: [0, 22, -30], color: '#c9b8ff', icon: '♾️',
      en: { kicker: 'The Universe', title: 'Two Trillion Galaxies', question: 'How many galaxies are there?',
        text: 'Astronomers think the universe we can see holds about two trillion galaxies, each with billions of stars. Hold a grain of sand up to the sky at arm\'s length: behind that tiny patch there are about ten thousand galaxies.' },
      zh: { kicker: '宇宙', title: '兩兆個星系', question: '宇宙裡有多少星系？',
        text: '天文學家認為，我們看得到的宇宙裡大約有兩兆個星系，每一個都有幾十億顆星星。把一粒沙子舉到手臂伸直的距離對著天空：那一小塊後面，大約藏著一萬個星系。' } }
  ],
  moons: [],
  facts: [
    { icon: '🕰️', en: { title: 'Looking back in time', text: 'The light from Andromeda took 2.5 million years to reach your eyes. You are seeing it as it was when our earliest ancestors were learning to make stone tools!' }, zh: { title: '看見過去', text: '仙女座星系的光花了 250 萬年才到你的眼睛。你看到的是它 250 萬年前的樣子，那時候我們最早的祖先才剛學會做石器！' } },
    { icon: '🔭', en: { title: 'A photo of almost nothing', text: 'Scientists once pointed the Hubble telescope at a tiny, empty-looking patch of sky for days. The picture came back full of about 10,000 galaxies!' }, zh: { title: '拍一片「什麼都沒有」的天空', text: '科學家曾經把哈伯望遠鏡對著一小塊看起來空空的天空拍了好幾天。結果照片裡塞了大約一萬個星系！' } },
    { icon: '🎈', en: { title: 'Galaxies are flying apart', text: 'Space itself is stretching, like the surface of a balloon being blown up, so almost all faraway galaxies are moving away from us. The farther they are, the faster they go.' }, zh: { title: '星系正在互相遠離', text: '太空本身正在拉長，像正在吹大的氣球表面，所以幾乎所有遙遠的星系都在離我們而去。越遠的跑得越快。' } },
    { icon: '🍩', en: { title: 'Black holes everywhere', text: 'Almost every big galaxy has a giant black hole in its middle. Some are billions of times heavier than the Sun, and the biggest ones shoot out jets of light longer than whole galaxies.' }, zh: { title: '到處都有黑洞', text: '幾乎每個大星系的中心都有一個巨大的黑洞。有些比太陽重幾十億倍，最大的還會噴出比整個星系還長的光柱。' } },
    { icon: '🐜', en: { title: 'Tiny galaxies too', text: 'Not all galaxies are giants. Dwarf galaxies have only a few million stars, and dozens of them buzz around the Milky Way like bees around a hive.' }, zh: { title: '也有迷你星系', text: '不是所有星系都很巨大。矮星系只有幾百萬顆星星，有幾十個像蜜蜂繞著蜂窩一樣繞著銀河系飛。' } }
  ]
};
