#!/usr/bin/env node
/* One-time neural voice generation for every knowledge card (Azure Speech).
   Idempotent: clips that already exist are skipped, so re-running never
   re-bills. Writes audio/<lang>/<id>.mp3 and audio/manifest.js.

   Usage:
     AZURE_SPEECH_KEY=xxxx AZURE_SPEECH_REGION=eastasia node tools/generate-audio.js [--dry-run] [--only sun,earth]
*/
const fs = require('fs');
const path = require('path');
const https = require('https');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const KEY = process.env.AZURE_SPEECH_KEY;
const REGION = process.env.AZURE_SPEECH_REGION || 'eastasia';
const DRY = process.argv.includes('--dry-run');
const onlyArg = process.argv.find(a => a.startsWith('--only='));
const ONLY = onlyArg ? onlyArg.slice(7).split(',') : null;

const VOICES = {
  zh: { name: 'zh-TW-HsiaoChenNeural', lang: 'zh-TW', rate: '-6%', pitch: '+2%' },
  en: { name: 'en-US-JennyNeural',     lang: 'en-US', rate: '-8%', pitch: '+2%' }
};

// Load content.js exactly as the browser sees it.
const sandbox = {};
vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'content.js'), 'utf8'), sandbox);
const CONTENT = sandbox.PLANET_CONTENT;
const OVERVIEW = sandbox.OVERVIEW_CONTENT;
const BEYOND = sandbox.BEYOND_CONTENT;

function jobs() {
  const out = [];
  const bodies = Object.assign({}, CONTENT, { overview: OVERVIEW, beyond: BEYOND, galaxy: sandbox.GALAXY_CONTENT, galaxies: sandbox.GALAXIES_CONTENT });
  for (const key of Object.keys(bodies)) {
    if (ONLY && !ONLY.includes(key)) continue;
    const d = bodies[key];
    for (const lang of ['zh', 'en']) {
      (d.hotspots || []).forEach((h, i) => out.push({ id: `${key}-hotspot-${i}-${lang}`, lang, text: `${h[lang].question} ${h[lang].text}` }));
      (d.features || []).forEach((f, i) => out.push({ id: `${key}-feature-${i}-${lang}`, lang, text: `${f[lang].question} ${f[lang].text}` }));
      (d.moons || []).forEach((m, i) => out.push({ id: `${key}-moon-${i}-${lang}`, lang, text: `${m[lang].subtitle} ${m[lang].text}` }));
      (d.dwarfs || []).forEach((m, i) => out.push({ id: `${key}-dwarf-${i}-${lang}`, lang, text: `${m[lang].subtitle} ${m[lang].text}` }));
      (d.facts || []).forEach((f, i) => out.push({ id: `${key}-fact-${i}-${lang}`, lang, text: f[lang].text }));
    }
  }
  return out;
}

function esc(s) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

function synth(job) {
  const v = VOICES[job.lang];
  const ssml = `<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="${v.lang}">` +
    `<voice name="${v.name}"><mstts:express-as style="friendly"><prosody rate="${v.rate}" pitch="${v.pitch}">${esc(job.text)}</prosody></mstts:express-as></voice></speak>`;
  return new Promise((resolve, reject) => {
    const req = https.request({
      method: 'POST', host: `${REGION}.tts.speech.microsoft.com`, path: '/cognitiveservices/v1',
      headers: {
        'Ocp-Apim-Subscription-Key': KEY,
        'Content-Type': 'application/ssml+xml',
        'X-Microsoft-OutputFormat': 'audio-24khz-96kbitrate-mono-mp3',
        'User-Agent': 'solar-system-explorer'
      }
    }, res => {
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => res.statusCode === 200 ? resolve(Buffer.concat(chunks)) : reject(new Error(`HTTP ${res.statusCode}: ${Buffer.concat(chunks).toString().slice(0, 200)}`)));
    });
    req.on('error', reject);
    req.end(ssml);
  });
}

function writeManifest() {
  const manifest = {};
  for (const lang of ['zh', 'en']) {
    const dir = path.join(ROOT, 'audio', lang);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) if (f.endsWith('.mp3')) manifest[f.replace(/\.mp3$/, '')] = `audio/${lang}/${f}`;
  }
  fs.writeFileSync(path.join(ROOT, 'audio', 'manifest.js'), '// Auto-generated by tools/generate-audio.js\nvar AUDIO_CLIPS = ' + JSON.stringify(manifest, null, 1) + ';\n');
  return Object.keys(manifest).length;
}

(async () => {
  const all = jobs();
  const todo = all.filter(j => !fs.existsSync(path.join(ROOT, 'audio', j.lang, j.id + '.mp3')));
  const chars = todo.reduce((n, j) => n + j.text.length, 0);
  console.log(`${all.length} clips total, ${todo.length} to generate (${chars.toLocaleString()} characters, ~free tier: 500k/month)`);
  if (DRY) { console.log('dry run — nothing sent.'); return; }
  if (!KEY) { console.error('Set AZURE_SPEECH_KEY (and AZURE_SPEECH_REGION) first.'); process.exit(1); }
  let done = 0;
  for (const j of todo) {
    const dir = path.join(ROOT, 'audio', j.lang);
    fs.mkdirSync(dir, { recursive: true });
    try {
      const mp3 = await synth(j);
      fs.writeFileSync(path.join(dir, j.id + '.mp3'), mp3);
      done++;
      process.stdout.write(`\r${done}/${todo.length} ${j.id}          `);
      await new Promise(r => setTimeout(r, 120)); // stay well under the request rate limit
    } catch (e) {
      console.error(`\nFailed ${j.id}: ${e.message}`);
    }
  }
  console.log(`\nwrote ${writeManifest()} clips into audio/manifest.js`);
})();
